// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.29.3

package fun.prof_chen.teamviewer.main_code.network.proto;

/**
 * Protobuf type {@code teamviewer.v1.AdminAck}
 */
public final class AdminAck extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:teamviewer.v1.AdminAck)
    AdminAckOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      AdminAck.class.getName());
  }
  // Use AdminAck.newBuilder() to construct.
  private AdminAck(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AdminAck() {
    action_ = "";
    error_ = "";
    command_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_AdminAck_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_AdminAck_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fun.prof_chen.teamviewer.main_code.network.proto.AdminAck.class, fun.prof_chen.teamviewer.main_code.network.proto.AdminAck.Builder.class);
  }

  private int bitField0_;
  private int detailCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object detail_;
  public enum DetailCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    PLAYER_MARK(10),
    CLEAR_ALL_PLAYER_MARKS(11),
    SAME_SERVER_FILTER(12),
    TACTICAL_WAYPOINT(13),
    WAYPOINTS_DELETE(14),
    DETAIL_NOT_SET(0);
    private final int value;
    private DetailCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DetailCase valueOf(int value) {
      return forNumber(value);
    }

    public static DetailCase forNumber(int value) {
      switch (value) {
        case 10: return PLAYER_MARK;
        case 11: return CLEAR_ALL_PLAYER_MARKS;
        case 12: return SAME_SERVER_FILTER;
        case 13: return TACTICAL_WAYPOINT;
        case 14: return WAYPOINTS_DELETE;
        case 0: return DETAIL_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DetailCase
  getDetailCase() {
    return DetailCase.forNumber(
        detailCase_);
  }

  public static final int OK_FIELD_NUMBER = 1;
  private boolean ok_ = false;
  /**
   * <code>bool ok = 1;</code>
   * @return The ok.
   */
  @java.lang.Override
  public boolean getOk() {
    return ok_;
  }

  public static final int ACTION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object action_ = "";
  /**
   * <code>optional string action = 2;</code>
   * @return Whether the action field is set.
   */
  @java.lang.Override
  public boolean hasAction() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string action = 2;</code>
   * @return The action.
   */
  @java.lang.Override
  public java.lang.String getAction() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      action_ = s;
      return s;
    }
  }
  /**
   * <code>optional string action = 2;</code>
   * @return The bytes for action.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActionBytes() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      action_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object error_ = "";
  /**
   * <code>optional string error = 3;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string error = 3;</code>
   * @return The error.
   */
  @java.lang.Override
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <code>optional string error = 3;</code>
   * @return The bytes for error.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMAND_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object command_ = "";
  /**
   * <code>optional string command = 4;</code>
   * @return Whether the command field is set.
   */
  @java.lang.Override
  public boolean hasCommand() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string command = 4;</code>
   * @return The command.
   */
  @java.lang.Override
  public java.lang.String getCommand() {
    java.lang.Object ref = command_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      command_ = s;
      return s;
    }
  }
  /**
   * <code>optional string command = 4;</code>
   * @return The bytes for command.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommandBytes() {
    java.lang.Object ref = command_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      command_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAYER_MARK_FIELD_NUMBER = 10;
  /**
   * <code>.teamviewer.v1.PlayerMarkAckDetail player_mark = 10;</code>
   * @return Whether the playerMark field is set.
   */
  @java.lang.Override
  public boolean hasPlayerMark() {
    return detailCase_ == 10;
  }
  /**
   * <code>.teamviewer.v1.PlayerMarkAckDetail player_mark = 10;</code>
   * @return The playerMark.
   */
  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail getPlayerMark() {
    if (detailCase_ == 10) {
       return (fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail) detail_;
    }
    return fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail.getDefaultInstance();
  }
  /**
   * <code>.teamviewer.v1.PlayerMarkAckDetail player_mark = 10;</code>
   */
  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetailOrBuilder getPlayerMarkOrBuilder() {
    if (detailCase_ == 10) {
       return (fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail) detail_;
    }
    return fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail.getDefaultInstance();
  }

  public static final int CLEAR_ALL_PLAYER_MARKS_FIELD_NUMBER = 11;
  /**
   * <code>.teamviewer.v1.ClearAllPlayerMarksAckDetail clear_all_player_marks = 11;</code>
   * @return Whether the clearAllPlayerMarks field is set.
   */
  @java.lang.Override
  public boolean hasClearAllPlayerMarks() {
    return detailCase_ == 11;
  }
  /**
   * <code>.teamviewer.v1.ClearAllPlayerMarksAckDetail clear_all_player_marks = 11;</code>
   * @return The clearAllPlayerMarks.
   */
  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail getClearAllPlayerMarks() {
    if (detailCase_ == 11) {
       return (fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail) detail_;
    }
    return fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail.getDefaultInstance();
  }
  /**
   * <code>.teamviewer.v1.ClearAllPlayerMarksAckDetail clear_all_player_marks = 11;</code>
   */
  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetailOrBuilder getClearAllPlayerMarksOrBuilder() {
    if (detailCase_ == 11) {
       return (fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail) detail_;
    }
    return fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail.getDefaultInstance();
  }

  public static final int SAME_SERVER_FILTER_FIELD_NUMBER = 12;
  /**
   * <code>.teamviewer.v1.SameServerFilterAckDetail same_server_filter = 12;</code>
   * @return Whether the sameServerFilter field is set.
   */
  @java.lang.Override
  public boolean hasSameServerFilter() {
    return detailCase_ == 12;
  }
  /**
   * <code>.teamviewer.v1.SameServerFilterAckDetail same_server_filter = 12;</code>
   * @return The sameServerFilter.
   */
  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail getSameServerFilter() {
    if (detailCase_ == 12) {
       return (fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail) detail_;
    }
    return fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail.getDefaultInstance();
  }
  /**
   * <code>.teamviewer.v1.SameServerFilterAckDetail same_server_filter = 12;</code>
   */
  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetailOrBuilder getSameServerFilterOrBuilder() {
    if (detailCase_ == 12) {
       return (fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail) detail_;
    }
    return fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail.getDefaultInstance();
  }

  public static final int TACTICAL_WAYPOINT_FIELD_NUMBER = 13;
  /**
   * <code>.teamviewer.v1.TacticalWaypointAckDetail tactical_waypoint = 13;</code>
   * @return Whether the tacticalWaypoint field is set.
   */
  @java.lang.Override
  public boolean hasTacticalWaypoint() {
    return detailCase_ == 13;
  }
  /**
   * <code>.teamviewer.v1.TacticalWaypointAckDetail tactical_waypoint = 13;</code>
   * @return The tacticalWaypoint.
   */
  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail getTacticalWaypoint() {
    if (detailCase_ == 13) {
       return (fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail) detail_;
    }
    return fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail.getDefaultInstance();
  }
  /**
   * <code>.teamviewer.v1.TacticalWaypointAckDetail tactical_waypoint = 13;</code>
   */
  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetailOrBuilder getTacticalWaypointOrBuilder() {
    if (detailCase_ == 13) {
       return (fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail) detail_;
    }
    return fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail.getDefaultInstance();
  }

  public static final int WAYPOINTS_DELETE_FIELD_NUMBER = 14;
  /**
   * <code>.teamviewer.v1.WaypointsDeleteAckDetail waypoints_delete = 14;</code>
   * @return Whether the waypointsDelete field is set.
   */
  @java.lang.Override
  public boolean hasWaypointsDelete() {
    return detailCase_ == 14;
  }
  /**
   * <code>.teamviewer.v1.WaypointsDeleteAckDetail waypoints_delete = 14;</code>
   * @return The waypointsDelete.
   */
  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail getWaypointsDelete() {
    if (detailCase_ == 14) {
       return (fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail) detail_;
    }
    return fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail.getDefaultInstance();
  }
  /**
   * <code>.teamviewer.v1.WaypointsDeleteAckDetail waypoints_delete = 14;</code>
   */
  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetailOrBuilder getWaypointsDeleteOrBuilder() {
    if (detailCase_ == 14) {
       return (fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail) detail_;
    }
    return fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ok_ != false) {
      output.writeBool(1, ok_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, action_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, error_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, command_);
    }
    if (detailCase_ == 10) {
      output.writeMessage(10, (fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail) detail_);
    }
    if (detailCase_ == 11) {
      output.writeMessage(11, (fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail) detail_);
    }
    if (detailCase_ == 12) {
      output.writeMessage(12, (fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail) detail_);
    }
    if (detailCase_ == 13) {
      output.writeMessage(13, (fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail) detail_);
    }
    if (detailCase_ == 14) {
      output.writeMessage(14, (fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail) detail_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ok_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, ok_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, action_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, error_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, command_);
    }
    if (detailCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, (fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail) detail_);
    }
    if (detailCase_ == 11) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, (fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail) detail_);
    }
    if (detailCase_ == 12) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, (fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail) detail_);
    }
    if (detailCase_ == 13) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, (fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail) detail_);
    }
    if (detailCase_ == 14) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, (fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail) detail_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fun.prof_chen.teamviewer.main_code.network.proto.AdminAck)) {
      return super.equals(obj);
    }
    fun.prof_chen.teamviewer.main_code.network.proto.AdminAck other = (fun.prof_chen.teamviewer.main_code.network.proto.AdminAck) obj;

    if (getOk()
        != other.getOk()) return false;
    if (hasAction() != other.hasAction()) return false;
    if (hasAction()) {
      if (!getAction()
          .equals(other.getAction())) return false;
    }
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (hasCommand() != other.hasCommand()) return false;
    if (hasCommand()) {
      if (!getCommand()
          .equals(other.getCommand())) return false;
    }
    if (!getDetailCase().equals(other.getDetailCase())) return false;
    switch (detailCase_) {
      case 10:
        if (!getPlayerMark()
            .equals(other.getPlayerMark())) return false;
        break;
      case 11:
        if (!getClearAllPlayerMarks()
            .equals(other.getClearAllPlayerMarks())) return false;
        break;
      case 12:
        if (!getSameServerFilter()
            .equals(other.getSameServerFilter())) return false;
        break;
      case 13:
        if (!getTacticalWaypoint()
            .equals(other.getTacticalWaypoint())) return false;
        break;
      case 14:
        if (!getWaypointsDelete()
            .equals(other.getWaypointsDelete())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOk());
    if (hasAction()) {
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
    }
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    if (hasCommand()) {
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + getCommand().hashCode();
    }
    switch (detailCase_) {
      case 10:
        hash = (37 * hash) + PLAYER_MARK_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerMark().hashCode();
        break;
      case 11:
        hash = (37 * hash) + CLEAR_ALL_PLAYER_MARKS_FIELD_NUMBER;
        hash = (53 * hash) + getClearAllPlayerMarks().hashCode();
        break;
      case 12:
        hash = (37 * hash) + SAME_SERVER_FILTER_FIELD_NUMBER;
        hash = (53 * hash) + getSameServerFilter().hashCode();
        break;
      case 13:
        hash = (37 * hash) + TACTICAL_WAYPOINT_FIELD_NUMBER;
        hash = (53 * hash) + getTacticalWaypoint().hashCode();
        break;
      case 14:
        hash = (37 * hash) + WAYPOINTS_DELETE_FIELD_NUMBER;
        hash = (53 * hash) + getWaypointsDelete().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.AdminAck parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.AdminAck parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.AdminAck parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.AdminAck parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.AdminAck parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.AdminAck parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.AdminAck parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.AdminAck parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.AdminAck parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.AdminAck parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.AdminAck parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.AdminAck parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fun.prof_chen.teamviewer.main_code.network.proto.AdminAck prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code teamviewer.v1.AdminAck}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:teamviewer.v1.AdminAck)
      fun.prof_chen.teamviewer.main_code.network.proto.AdminAckOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_AdminAck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_AdminAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fun.prof_chen.teamviewer.main_code.network.proto.AdminAck.class, fun.prof_chen.teamviewer.main_code.network.proto.AdminAck.Builder.class);
    }

    // Construct using fun.prof_chen.teamviewer.main_code.network.proto.AdminAck.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ok_ = false;
      action_ = "";
      error_ = "";
      command_ = "";
      if (playerMarkBuilder_ != null) {
        playerMarkBuilder_.clear();
      }
      if (clearAllPlayerMarksBuilder_ != null) {
        clearAllPlayerMarksBuilder_.clear();
      }
      if (sameServerFilterBuilder_ != null) {
        sameServerFilterBuilder_.clear();
      }
      if (tacticalWaypointBuilder_ != null) {
        tacticalWaypointBuilder_.clear();
      }
      if (waypointsDeleteBuilder_ != null) {
        waypointsDeleteBuilder_.clear();
      }
      detailCase_ = 0;
      detail_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_AdminAck_descriptor;
    }

    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.AdminAck getDefaultInstanceForType() {
      return fun.prof_chen.teamviewer.main_code.network.proto.AdminAck.getDefaultInstance();
    }

    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.AdminAck build() {
      fun.prof_chen.teamviewer.main_code.network.proto.AdminAck result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.AdminAck buildPartial() {
      fun.prof_chen.teamviewer.main_code.network.proto.AdminAck result = new fun.prof_chen.teamviewer.main_code.network.proto.AdminAck(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(fun.prof_chen.teamviewer.main_code.network.proto.AdminAck result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ok_ = ok_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.action_ = action_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.error_ = error_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.command_ = command_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private void buildPartialOneofs(fun.prof_chen.teamviewer.main_code.network.proto.AdminAck result) {
      result.detailCase_ = detailCase_;
      result.detail_ = this.detail_;
      if (detailCase_ == 10 &&
          playerMarkBuilder_ != null) {
        result.detail_ = playerMarkBuilder_.build();
      }
      if (detailCase_ == 11 &&
          clearAllPlayerMarksBuilder_ != null) {
        result.detail_ = clearAllPlayerMarksBuilder_.build();
      }
      if (detailCase_ == 12 &&
          sameServerFilterBuilder_ != null) {
        result.detail_ = sameServerFilterBuilder_.build();
      }
      if (detailCase_ == 13 &&
          tacticalWaypointBuilder_ != null) {
        result.detail_ = tacticalWaypointBuilder_.build();
      }
      if (detailCase_ == 14 &&
          waypointsDeleteBuilder_ != null) {
        result.detail_ = waypointsDeleteBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fun.prof_chen.teamviewer.main_code.network.proto.AdminAck) {
        return mergeFrom((fun.prof_chen.teamviewer.main_code.network.proto.AdminAck)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fun.prof_chen.teamviewer.main_code.network.proto.AdminAck other) {
      if (other == fun.prof_chen.teamviewer.main_code.network.proto.AdminAck.getDefaultInstance()) return this;
      if (other.getOk() != false) {
        setOk(other.getOk());
      }
      if (other.hasAction()) {
        action_ = other.action_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasError()) {
        error_ = other.error_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasCommand()) {
        command_ = other.command_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      switch (other.getDetailCase()) {
        case PLAYER_MARK: {
          mergePlayerMark(other.getPlayerMark());
          break;
        }
        case CLEAR_ALL_PLAYER_MARKS: {
          mergeClearAllPlayerMarks(other.getClearAllPlayerMarks());
          break;
        }
        case SAME_SERVER_FILTER: {
          mergeSameServerFilter(other.getSameServerFilter());
          break;
        }
        case TACTICAL_WAYPOINT: {
          mergeTacticalWaypoint(other.getTacticalWaypoint());
          break;
        }
        case WAYPOINTS_DELETE: {
          mergeWaypointsDelete(other.getWaypointsDelete());
          break;
        }
        case DETAIL_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              ok_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              action_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              error_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              command_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 82: {
              input.readMessage(
                  getPlayerMarkFieldBuilder().getBuilder(),
                  extensionRegistry);
              detailCase_ = 10;
              break;
            } // case 82
            case 90: {
              input.readMessage(
                  getClearAllPlayerMarksFieldBuilder().getBuilder(),
                  extensionRegistry);
              detailCase_ = 11;
              break;
            } // case 90
            case 98: {
              input.readMessage(
                  getSameServerFilterFieldBuilder().getBuilder(),
                  extensionRegistry);
              detailCase_ = 12;
              break;
            } // case 98
            case 106: {
              input.readMessage(
                  getTacticalWaypointFieldBuilder().getBuilder(),
                  extensionRegistry);
              detailCase_ = 13;
              break;
            } // case 106
            case 114: {
              input.readMessage(
                  getWaypointsDeleteFieldBuilder().getBuilder(),
                  extensionRegistry);
              detailCase_ = 14;
              break;
            } // case 114
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int detailCase_ = 0;
    private java.lang.Object detail_;
    public DetailCase
        getDetailCase() {
      return DetailCase.forNumber(
          detailCase_);
    }

    public Builder clearDetail() {
      detailCase_ = 0;
      detail_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private boolean ok_ ;
    /**
     * <code>bool ok = 1;</code>
     * @return The ok.
     */
    @java.lang.Override
    public boolean getOk() {
      return ok_;
    }
    /**
     * <code>bool ok = 1;</code>
     * @param value The ok to set.
     * @return This builder for chaining.
     */
    public Builder setOk(boolean value) {

      ok_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool ok = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOk() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ok_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object action_ = "";
    /**
     * <code>optional string action = 2;</code>
     * @return Whether the action field is set.
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string action = 2;</code>
     * @return The action.
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string action = 2;</code>
     * @return The bytes for action.
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string action = 2;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      action_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string action = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      action_ = getDefaultInstance().getAction();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string action = 2;</code>
     * @param value The bytes for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      action_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object error_ = "";
    /**
     * <code>optional string error = 3;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string error = 3;</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string error = 3;</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string error = 3;</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      error_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string error = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      error_ = getDefaultInstance().getError();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string error = 3;</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      error_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object command_ = "";
    /**
     * <code>optional string command = 4;</code>
     * @return Whether the command field is set.
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string command = 4;</code>
     * @return The command.
     */
    public java.lang.String getCommand() {
      java.lang.Object ref = command_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        command_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string command = 4;</code>
     * @return The bytes for command.
     */
    public com.google.protobuf.ByteString
        getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string command = 4;</code>
     * @param value The command to set.
     * @return This builder for chaining.
     */
    public Builder setCommand(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      command_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string command = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommand() {
      command_ = getDefaultInstance().getCommand();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string command = 4;</code>
     * @param value The bytes for command to set.
     * @return This builder for chaining.
     */
    public Builder setCommandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      command_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail, fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail.Builder, fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetailOrBuilder> playerMarkBuilder_;
    /**
     * <code>.teamviewer.v1.PlayerMarkAckDetail player_mark = 10;</code>
     * @return Whether the playerMark field is set.
     */
    @java.lang.Override
    public boolean hasPlayerMark() {
      return detailCase_ == 10;
    }
    /**
     * <code>.teamviewer.v1.PlayerMarkAckDetail player_mark = 10;</code>
     * @return The playerMark.
     */
    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail getPlayerMark() {
      if (playerMarkBuilder_ == null) {
        if (detailCase_ == 10) {
          return (fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail) detail_;
        }
        return fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail.getDefaultInstance();
      } else {
        if (detailCase_ == 10) {
          return playerMarkBuilder_.getMessage();
        }
        return fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail.getDefaultInstance();
      }
    }
    /**
     * <code>.teamviewer.v1.PlayerMarkAckDetail player_mark = 10;</code>
     */
    public Builder setPlayerMark(fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail value) {
      if (playerMarkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        detail_ = value;
        onChanged();
      } else {
        playerMarkBuilder_.setMessage(value);
      }
      detailCase_ = 10;
      return this;
    }
    /**
     * <code>.teamviewer.v1.PlayerMarkAckDetail player_mark = 10;</code>
     */
    public Builder setPlayerMark(
        fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail.Builder builderForValue) {
      if (playerMarkBuilder_ == null) {
        detail_ = builderForValue.build();
        onChanged();
      } else {
        playerMarkBuilder_.setMessage(builderForValue.build());
      }
      detailCase_ = 10;
      return this;
    }
    /**
     * <code>.teamviewer.v1.PlayerMarkAckDetail player_mark = 10;</code>
     */
    public Builder mergePlayerMark(fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail value) {
      if (playerMarkBuilder_ == null) {
        if (detailCase_ == 10 &&
            detail_ != fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail.getDefaultInstance()) {
          detail_ = fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail.newBuilder((fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail) detail_)
              .mergeFrom(value).buildPartial();
        } else {
          detail_ = value;
        }
        onChanged();
      } else {
        if (detailCase_ == 10) {
          playerMarkBuilder_.mergeFrom(value);
        } else {
          playerMarkBuilder_.setMessage(value);
        }
      }
      detailCase_ = 10;
      return this;
    }
    /**
     * <code>.teamviewer.v1.PlayerMarkAckDetail player_mark = 10;</code>
     */
    public Builder clearPlayerMark() {
      if (playerMarkBuilder_ == null) {
        if (detailCase_ == 10) {
          detailCase_ = 0;
          detail_ = null;
          onChanged();
        }
      } else {
        if (detailCase_ == 10) {
          detailCase_ = 0;
          detail_ = null;
        }
        playerMarkBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.teamviewer.v1.PlayerMarkAckDetail player_mark = 10;</code>
     */
    public fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail.Builder getPlayerMarkBuilder() {
      return getPlayerMarkFieldBuilder().getBuilder();
    }
    /**
     * <code>.teamviewer.v1.PlayerMarkAckDetail player_mark = 10;</code>
     */
    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetailOrBuilder getPlayerMarkOrBuilder() {
      if ((detailCase_ == 10) && (playerMarkBuilder_ != null)) {
        return playerMarkBuilder_.getMessageOrBuilder();
      } else {
        if (detailCase_ == 10) {
          return (fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail) detail_;
        }
        return fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail.getDefaultInstance();
      }
    }
    /**
     * <code>.teamviewer.v1.PlayerMarkAckDetail player_mark = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail, fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail.Builder, fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetailOrBuilder> 
        getPlayerMarkFieldBuilder() {
      if (playerMarkBuilder_ == null) {
        if (!(detailCase_ == 10)) {
          detail_ = fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail.getDefaultInstance();
        }
        playerMarkBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail, fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail.Builder, fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetailOrBuilder>(
                (fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkAckDetail) detail_,
                getParentForChildren(),
                isClean());
        detail_ = null;
      }
      detailCase_ = 10;
      onChanged();
      return playerMarkBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail, fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail.Builder, fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetailOrBuilder> clearAllPlayerMarksBuilder_;
    /**
     * <code>.teamviewer.v1.ClearAllPlayerMarksAckDetail clear_all_player_marks = 11;</code>
     * @return Whether the clearAllPlayerMarks field is set.
     */
    @java.lang.Override
    public boolean hasClearAllPlayerMarks() {
      return detailCase_ == 11;
    }
    /**
     * <code>.teamviewer.v1.ClearAllPlayerMarksAckDetail clear_all_player_marks = 11;</code>
     * @return The clearAllPlayerMarks.
     */
    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail getClearAllPlayerMarks() {
      if (clearAllPlayerMarksBuilder_ == null) {
        if (detailCase_ == 11) {
          return (fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail) detail_;
        }
        return fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail.getDefaultInstance();
      } else {
        if (detailCase_ == 11) {
          return clearAllPlayerMarksBuilder_.getMessage();
        }
        return fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail.getDefaultInstance();
      }
    }
    /**
     * <code>.teamviewer.v1.ClearAllPlayerMarksAckDetail clear_all_player_marks = 11;</code>
     */
    public Builder setClearAllPlayerMarks(fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail value) {
      if (clearAllPlayerMarksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        detail_ = value;
        onChanged();
      } else {
        clearAllPlayerMarksBuilder_.setMessage(value);
      }
      detailCase_ = 11;
      return this;
    }
    /**
     * <code>.teamviewer.v1.ClearAllPlayerMarksAckDetail clear_all_player_marks = 11;</code>
     */
    public Builder setClearAllPlayerMarks(
        fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail.Builder builderForValue) {
      if (clearAllPlayerMarksBuilder_ == null) {
        detail_ = builderForValue.build();
        onChanged();
      } else {
        clearAllPlayerMarksBuilder_.setMessage(builderForValue.build());
      }
      detailCase_ = 11;
      return this;
    }
    /**
     * <code>.teamviewer.v1.ClearAllPlayerMarksAckDetail clear_all_player_marks = 11;</code>
     */
    public Builder mergeClearAllPlayerMarks(fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail value) {
      if (clearAllPlayerMarksBuilder_ == null) {
        if (detailCase_ == 11 &&
            detail_ != fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail.getDefaultInstance()) {
          detail_ = fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail.newBuilder((fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail) detail_)
              .mergeFrom(value).buildPartial();
        } else {
          detail_ = value;
        }
        onChanged();
      } else {
        if (detailCase_ == 11) {
          clearAllPlayerMarksBuilder_.mergeFrom(value);
        } else {
          clearAllPlayerMarksBuilder_.setMessage(value);
        }
      }
      detailCase_ = 11;
      return this;
    }
    /**
     * <code>.teamviewer.v1.ClearAllPlayerMarksAckDetail clear_all_player_marks = 11;</code>
     */
    public Builder clearClearAllPlayerMarks() {
      if (clearAllPlayerMarksBuilder_ == null) {
        if (detailCase_ == 11) {
          detailCase_ = 0;
          detail_ = null;
          onChanged();
        }
      } else {
        if (detailCase_ == 11) {
          detailCase_ = 0;
          detail_ = null;
        }
        clearAllPlayerMarksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.teamviewer.v1.ClearAllPlayerMarksAckDetail clear_all_player_marks = 11;</code>
     */
    public fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail.Builder getClearAllPlayerMarksBuilder() {
      return getClearAllPlayerMarksFieldBuilder().getBuilder();
    }
    /**
     * <code>.teamviewer.v1.ClearAllPlayerMarksAckDetail clear_all_player_marks = 11;</code>
     */
    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetailOrBuilder getClearAllPlayerMarksOrBuilder() {
      if ((detailCase_ == 11) && (clearAllPlayerMarksBuilder_ != null)) {
        return clearAllPlayerMarksBuilder_.getMessageOrBuilder();
      } else {
        if (detailCase_ == 11) {
          return (fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail) detail_;
        }
        return fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail.getDefaultInstance();
      }
    }
    /**
     * <code>.teamviewer.v1.ClearAllPlayerMarksAckDetail clear_all_player_marks = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail, fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail.Builder, fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetailOrBuilder> 
        getClearAllPlayerMarksFieldBuilder() {
      if (clearAllPlayerMarksBuilder_ == null) {
        if (!(detailCase_ == 11)) {
          detail_ = fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail.getDefaultInstance();
        }
        clearAllPlayerMarksBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail, fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail.Builder, fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetailOrBuilder>(
                (fun.prof_chen.teamviewer.main_code.network.proto.ClearAllPlayerMarksAckDetail) detail_,
                getParentForChildren(),
                isClean());
        detail_ = null;
      }
      detailCase_ = 11;
      onChanged();
      return clearAllPlayerMarksBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail, fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail.Builder, fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetailOrBuilder> sameServerFilterBuilder_;
    /**
     * <code>.teamviewer.v1.SameServerFilterAckDetail same_server_filter = 12;</code>
     * @return Whether the sameServerFilter field is set.
     */
    @java.lang.Override
    public boolean hasSameServerFilter() {
      return detailCase_ == 12;
    }
    /**
     * <code>.teamviewer.v1.SameServerFilterAckDetail same_server_filter = 12;</code>
     * @return The sameServerFilter.
     */
    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail getSameServerFilter() {
      if (sameServerFilterBuilder_ == null) {
        if (detailCase_ == 12) {
          return (fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail) detail_;
        }
        return fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail.getDefaultInstance();
      } else {
        if (detailCase_ == 12) {
          return sameServerFilterBuilder_.getMessage();
        }
        return fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail.getDefaultInstance();
      }
    }
    /**
     * <code>.teamviewer.v1.SameServerFilterAckDetail same_server_filter = 12;</code>
     */
    public Builder setSameServerFilter(fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail value) {
      if (sameServerFilterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        detail_ = value;
        onChanged();
      } else {
        sameServerFilterBuilder_.setMessage(value);
      }
      detailCase_ = 12;
      return this;
    }
    /**
     * <code>.teamviewer.v1.SameServerFilterAckDetail same_server_filter = 12;</code>
     */
    public Builder setSameServerFilter(
        fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail.Builder builderForValue) {
      if (sameServerFilterBuilder_ == null) {
        detail_ = builderForValue.build();
        onChanged();
      } else {
        sameServerFilterBuilder_.setMessage(builderForValue.build());
      }
      detailCase_ = 12;
      return this;
    }
    /**
     * <code>.teamviewer.v1.SameServerFilterAckDetail same_server_filter = 12;</code>
     */
    public Builder mergeSameServerFilter(fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail value) {
      if (sameServerFilterBuilder_ == null) {
        if (detailCase_ == 12 &&
            detail_ != fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail.getDefaultInstance()) {
          detail_ = fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail.newBuilder((fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail) detail_)
              .mergeFrom(value).buildPartial();
        } else {
          detail_ = value;
        }
        onChanged();
      } else {
        if (detailCase_ == 12) {
          sameServerFilterBuilder_.mergeFrom(value);
        } else {
          sameServerFilterBuilder_.setMessage(value);
        }
      }
      detailCase_ = 12;
      return this;
    }
    /**
     * <code>.teamviewer.v1.SameServerFilterAckDetail same_server_filter = 12;</code>
     */
    public Builder clearSameServerFilter() {
      if (sameServerFilterBuilder_ == null) {
        if (detailCase_ == 12) {
          detailCase_ = 0;
          detail_ = null;
          onChanged();
        }
      } else {
        if (detailCase_ == 12) {
          detailCase_ = 0;
          detail_ = null;
        }
        sameServerFilterBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.teamviewer.v1.SameServerFilterAckDetail same_server_filter = 12;</code>
     */
    public fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail.Builder getSameServerFilterBuilder() {
      return getSameServerFilterFieldBuilder().getBuilder();
    }
    /**
     * <code>.teamviewer.v1.SameServerFilterAckDetail same_server_filter = 12;</code>
     */
    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetailOrBuilder getSameServerFilterOrBuilder() {
      if ((detailCase_ == 12) && (sameServerFilterBuilder_ != null)) {
        return sameServerFilterBuilder_.getMessageOrBuilder();
      } else {
        if (detailCase_ == 12) {
          return (fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail) detail_;
        }
        return fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail.getDefaultInstance();
      }
    }
    /**
     * <code>.teamviewer.v1.SameServerFilterAckDetail same_server_filter = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail, fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail.Builder, fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetailOrBuilder> 
        getSameServerFilterFieldBuilder() {
      if (sameServerFilterBuilder_ == null) {
        if (!(detailCase_ == 12)) {
          detail_ = fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail.getDefaultInstance();
        }
        sameServerFilterBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail, fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail.Builder, fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetailOrBuilder>(
                (fun.prof_chen.teamviewer.main_code.network.proto.SameServerFilterAckDetail) detail_,
                getParentForChildren(),
                isClean());
        detail_ = null;
      }
      detailCase_ = 12;
      onChanged();
      return sameServerFilterBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail, fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail.Builder, fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetailOrBuilder> tacticalWaypointBuilder_;
    /**
     * <code>.teamviewer.v1.TacticalWaypointAckDetail tactical_waypoint = 13;</code>
     * @return Whether the tacticalWaypoint field is set.
     */
    @java.lang.Override
    public boolean hasTacticalWaypoint() {
      return detailCase_ == 13;
    }
    /**
     * <code>.teamviewer.v1.TacticalWaypointAckDetail tactical_waypoint = 13;</code>
     * @return The tacticalWaypoint.
     */
    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail getTacticalWaypoint() {
      if (tacticalWaypointBuilder_ == null) {
        if (detailCase_ == 13) {
          return (fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail) detail_;
        }
        return fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail.getDefaultInstance();
      } else {
        if (detailCase_ == 13) {
          return tacticalWaypointBuilder_.getMessage();
        }
        return fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail.getDefaultInstance();
      }
    }
    /**
     * <code>.teamviewer.v1.TacticalWaypointAckDetail tactical_waypoint = 13;</code>
     */
    public Builder setTacticalWaypoint(fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail value) {
      if (tacticalWaypointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        detail_ = value;
        onChanged();
      } else {
        tacticalWaypointBuilder_.setMessage(value);
      }
      detailCase_ = 13;
      return this;
    }
    /**
     * <code>.teamviewer.v1.TacticalWaypointAckDetail tactical_waypoint = 13;</code>
     */
    public Builder setTacticalWaypoint(
        fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail.Builder builderForValue) {
      if (tacticalWaypointBuilder_ == null) {
        detail_ = builderForValue.build();
        onChanged();
      } else {
        tacticalWaypointBuilder_.setMessage(builderForValue.build());
      }
      detailCase_ = 13;
      return this;
    }
    /**
     * <code>.teamviewer.v1.TacticalWaypointAckDetail tactical_waypoint = 13;</code>
     */
    public Builder mergeTacticalWaypoint(fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail value) {
      if (tacticalWaypointBuilder_ == null) {
        if (detailCase_ == 13 &&
            detail_ != fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail.getDefaultInstance()) {
          detail_ = fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail.newBuilder((fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail) detail_)
              .mergeFrom(value).buildPartial();
        } else {
          detail_ = value;
        }
        onChanged();
      } else {
        if (detailCase_ == 13) {
          tacticalWaypointBuilder_.mergeFrom(value);
        } else {
          tacticalWaypointBuilder_.setMessage(value);
        }
      }
      detailCase_ = 13;
      return this;
    }
    /**
     * <code>.teamviewer.v1.TacticalWaypointAckDetail tactical_waypoint = 13;</code>
     */
    public Builder clearTacticalWaypoint() {
      if (tacticalWaypointBuilder_ == null) {
        if (detailCase_ == 13) {
          detailCase_ = 0;
          detail_ = null;
          onChanged();
        }
      } else {
        if (detailCase_ == 13) {
          detailCase_ = 0;
          detail_ = null;
        }
        tacticalWaypointBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.teamviewer.v1.TacticalWaypointAckDetail tactical_waypoint = 13;</code>
     */
    public fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail.Builder getTacticalWaypointBuilder() {
      return getTacticalWaypointFieldBuilder().getBuilder();
    }
    /**
     * <code>.teamviewer.v1.TacticalWaypointAckDetail tactical_waypoint = 13;</code>
     */
    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetailOrBuilder getTacticalWaypointOrBuilder() {
      if ((detailCase_ == 13) && (tacticalWaypointBuilder_ != null)) {
        return tacticalWaypointBuilder_.getMessageOrBuilder();
      } else {
        if (detailCase_ == 13) {
          return (fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail) detail_;
        }
        return fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail.getDefaultInstance();
      }
    }
    /**
     * <code>.teamviewer.v1.TacticalWaypointAckDetail tactical_waypoint = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail, fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail.Builder, fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetailOrBuilder> 
        getTacticalWaypointFieldBuilder() {
      if (tacticalWaypointBuilder_ == null) {
        if (!(detailCase_ == 13)) {
          detail_ = fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail.getDefaultInstance();
        }
        tacticalWaypointBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail, fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail.Builder, fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetailOrBuilder>(
                (fun.prof_chen.teamviewer.main_code.network.proto.TacticalWaypointAckDetail) detail_,
                getParentForChildren(),
                isClean());
        detail_ = null;
      }
      detailCase_ = 13;
      onChanged();
      return tacticalWaypointBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail, fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail.Builder, fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetailOrBuilder> waypointsDeleteBuilder_;
    /**
     * <code>.teamviewer.v1.WaypointsDeleteAckDetail waypoints_delete = 14;</code>
     * @return Whether the waypointsDelete field is set.
     */
    @java.lang.Override
    public boolean hasWaypointsDelete() {
      return detailCase_ == 14;
    }
    /**
     * <code>.teamviewer.v1.WaypointsDeleteAckDetail waypoints_delete = 14;</code>
     * @return The waypointsDelete.
     */
    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail getWaypointsDelete() {
      if (waypointsDeleteBuilder_ == null) {
        if (detailCase_ == 14) {
          return (fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail) detail_;
        }
        return fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail.getDefaultInstance();
      } else {
        if (detailCase_ == 14) {
          return waypointsDeleteBuilder_.getMessage();
        }
        return fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail.getDefaultInstance();
      }
    }
    /**
     * <code>.teamviewer.v1.WaypointsDeleteAckDetail waypoints_delete = 14;</code>
     */
    public Builder setWaypointsDelete(fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail value) {
      if (waypointsDeleteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        detail_ = value;
        onChanged();
      } else {
        waypointsDeleteBuilder_.setMessage(value);
      }
      detailCase_ = 14;
      return this;
    }
    /**
     * <code>.teamviewer.v1.WaypointsDeleteAckDetail waypoints_delete = 14;</code>
     */
    public Builder setWaypointsDelete(
        fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail.Builder builderForValue) {
      if (waypointsDeleteBuilder_ == null) {
        detail_ = builderForValue.build();
        onChanged();
      } else {
        waypointsDeleteBuilder_.setMessage(builderForValue.build());
      }
      detailCase_ = 14;
      return this;
    }
    /**
     * <code>.teamviewer.v1.WaypointsDeleteAckDetail waypoints_delete = 14;</code>
     */
    public Builder mergeWaypointsDelete(fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail value) {
      if (waypointsDeleteBuilder_ == null) {
        if (detailCase_ == 14 &&
            detail_ != fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail.getDefaultInstance()) {
          detail_ = fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail.newBuilder((fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail) detail_)
              .mergeFrom(value).buildPartial();
        } else {
          detail_ = value;
        }
        onChanged();
      } else {
        if (detailCase_ == 14) {
          waypointsDeleteBuilder_.mergeFrom(value);
        } else {
          waypointsDeleteBuilder_.setMessage(value);
        }
      }
      detailCase_ = 14;
      return this;
    }
    /**
     * <code>.teamviewer.v1.WaypointsDeleteAckDetail waypoints_delete = 14;</code>
     */
    public Builder clearWaypointsDelete() {
      if (waypointsDeleteBuilder_ == null) {
        if (detailCase_ == 14) {
          detailCase_ = 0;
          detail_ = null;
          onChanged();
        }
      } else {
        if (detailCase_ == 14) {
          detailCase_ = 0;
          detail_ = null;
        }
        waypointsDeleteBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.teamviewer.v1.WaypointsDeleteAckDetail waypoints_delete = 14;</code>
     */
    public fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail.Builder getWaypointsDeleteBuilder() {
      return getWaypointsDeleteFieldBuilder().getBuilder();
    }
    /**
     * <code>.teamviewer.v1.WaypointsDeleteAckDetail waypoints_delete = 14;</code>
     */
    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetailOrBuilder getWaypointsDeleteOrBuilder() {
      if ((detailCase_ == 14) && (waypointsDeleteBuilder_ != null)) {
        return waypointsDeleteBuilder_.getMessageOrBuilder();
      } else {
        if (detailCase_ == 14) {
          return (fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail) detail_;
        }
        return fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail.getDefaultInstance();
      }
    }
    /**
     * <code>.teamviewer.v1.WaypointsDeleteAckDetail waypoints_delete = 14;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail, fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail.Builder, fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetailOrBuilder> 
        getWaypointsDeleteFieldBuilder() {
      if (waypointsDeleteBuilder_ == null) {
        if (!(detailCase_ == 14)) {
          detail_ = fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail.getDefaultInstance();
        }
        waypointsDeleteBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail, fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail.Builder, fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetailOrBuilder>(
                (fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteAckDetail) detail_,
                getParentForChildren(),
                isClean());
        detail_ = null;
      }
      detailCase_ = 14;
      onChanged();
      return waypointsDeleteBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:teamviewer.v1.AdminAck)
  }

  // @@protoc_insertion_point(class_scope:teamviewer.v1.AdminAck)
  private static final fun.prof_chen.teamviewer.main_code.network.proto.AdminAck DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fun.prof_chen.teamviewer.main_code.network.proto.AdminAck();
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.AdminAck getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdminAck>
      PARSER = new com.google.protobuf.AbstractParser<AdminAck>() {
    @java.lang.Override
    public AdminAck parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AdminAck> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdminAck> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.AdminAck getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

