// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

/**
 * Protobuf type {@code teamviewer.v1.BattleMapObservation}
 */
@com.google.protobuf.Generated
public final class BattleMapObservation extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:teamviewer.v1.BattleMapObservation)
    BattleMapObservationOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "BattleMapObservation");
  }
  // Use BattleMapObservation.newBuilder() to construct.
  private BattleMapObservation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BattleMapObservation() {
    dimension_ = "";
    candidates_ = java.util.Collections.emptyList();
    cells_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_BattleMapObservation_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_BattleMapObservation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_BattleMapObservation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation.class, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation.Builder.class);
  }

  public static final int DIMENSION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dimension_ = "";
  /**
   * <code>string dimension = 1 [json_name = "dimension"];</code>
   * @return The dimension.
   */
  @java.lang.Override
  public java.lang.String getDimension() {
    java.lang.Object ref = dimension_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dimension_ = s;
      return s;
    }
  }
  /**
   * <code>string dimension = 1 [json_name = "dimension"];</code>
   * @return The bytes for dimension.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDimensionBytes() {
    java.lang.Object ref = dimension_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dimension_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAP_SIZE_FIELD_NUMBER = 2;
  private int mapSize_ = 0;
  /**
   * <code>int32 map_size = 2 [json_name = "mapSize"];</code>
   * @return The mapSize.
   */
  @java.lang.Override
  public int getMapSize() {
    return mapSize_;
  }

  public static final int ANCHOR_ROW_FIELD_NUMBER = 3;
  private int anchorRow_ = 0;
  /**
   * <code>int32 anchor_row = 3 [json_name = "anchorRow"];</code>
   * @return The anchorRow.
   */
  @java.lang.Override
  public int getAnchorRow() {
    return anchorRow_;
  }

  public static final int ANCHOR_COL_FIELD_NUMBER = 4;
  private int anchorCol_ = 0;
  /**
   * <code>int32 anchor_col = 4 [json_name = "anchorCol"];</code>
   * @return The anchorCol.
   */
  @java.lang.Override
  public int getAnchorCol() {
    return anchorCol_;
  }

  public static final int SNAPSHOT_OBSERVED_AT_FIELD_NUMBER = 5;
  private long snapshotObservedAt_ = 0L;
  /**
   * <code>int64 snapshot_observed_at = 5 [json_name = "snapshotObservedAt"];</code>
   * @return The snapshotObservedAt.
   */
  @java.lang.Override
  public long getSnapshotObservedAt() {
    return snapshotObservedAt_;
  }

  public static final int PARSED_AT_FIELD_NUMBER = 6;
  private long parsedAt_ = 0L;
  /**
   * <code>int64 parsed_at = 6 [json_name = "parsedAt"];</code>
   * @return The parsedAt.
   */
  @java.lang.Override
  public long getParsedAt() {
    return parsedAt_;
  }

  public static final int CANDIDATES_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private java.util.List<fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate> candidates_;
  /**
   * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
   */
  @java.lang.Override
  public java.util.List<fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate> getCandidatesList() {
    return candidates_;
  }
  /**
   * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidateOrBuilder> 
      getCandidatesOrBuilderList() {
    return candidates_;
  }
  /**
   * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
   */
  @java.lang.Override
  public int getCandidatesCount() {
    return candidates_.size();
  }
  /**
   * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
   */
  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate getCandidates(int index) {
    return candidates_.get(index);
  }
  /**
   * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
   */
  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidateOrBuilder getCandidatesOrBuilder(
      int index) {
    return candidates_.get(index);
  }

  public static final int CELLS_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private java.util.List<fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell> cells_;
  /**
   * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
   */
  @java.lang.Override
  public java.util.List<fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell> getCellsList() {
    return cells_;
  }
  /**
   * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCellOrBuilder> 
      getCellsOrBuilderList() {
    return cells_;
  }
  /**
   * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
   */
  @java.lang.Override
  public int getCellsCount() {
    return cells_.size();
  }
  /**
   * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
   */
  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell getCells(int index) {
    return cells_.get(index);
  }
  /**
   * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
   */
  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCellOrBuilder getCellsOrBuilder(
      int index) {
    return cells_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dimension_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, dimension_);
    }
    if (mapSize_ != 0) {
      output.writeInt32(2, mapSize_);
    }
    if (anchorRow_ != 0) {
      output.writeInt32(3, anchorRow_);
    }
    if (anchorCol_ != 0) {
      output.writeInt32(4, anchorCol_);
    }
    if (snapshotObservedAt_ != 0L) {
      output.writeInt64(5, snapshotObservedAt_);
    }
    if (parsedAt_ != 0L) {
      output.writeInt64(6, parsedAt_);
    }
    for (int i = 0; i < candidates_.size(); i++) {
      output.writeMessage(7, candidates_.get(i));
    }
    for (int i = 0; i < cells_.size(); i++) {
      output.writeMessage(8, cells_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dimension_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, dimension_);
    }
    if (mapSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, mapSize_);
    }
    if (anchorRow_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, anchorRow_);
    }
    if (anchorCol_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, anchorCol_);
    }
    if (snapshotObservedAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, snapshotObservedAt_);
    }
    if (parsedAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, parsedAt_);
    }

        {
          final int count = candidates_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(candidates_.get(i));
          }
          size += 1 * count;
        }

        {
          final int count = cells_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(cells_.get(i));
          }
          size += 1 * count;
        }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation)) {
      return super.equals(obj);
    }
    fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation other = (fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation) obj;

    if (!getDimension()
        .equals(other.getDimension())) return false;
    if (getMapSize()
        != other.getMapSize()) return false;
    if (getAnchorRow()
        != other.getAnchorRow()) return false;
    if (getAnchorCol()
        != other.getAnchorCol()) return false;
    if (getSnapshotObservedAt()
        != other.getSnapshotObservedAt()) return false;
    if (getParsedAt()
        != other.getParsedAt()) return false;
    if (!getCandidatesList()
        .equals(other.getCandidatesList())) return false;
    if (!getCellsList()
        .equals(other.getCellsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DIMENSION_FIELD_NUMBER;
    hash = (53 * hash) + getDimension().hashCode();
    hash = (37 * hash) + MAP_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getMapSize();
    hash = (37 * hash) + ANCHOR_ROW_FIELD_NUMBER;
    hash = (53 * hash) + getAnchorRow();
    hash = (37 * hash) + ANCHOR_COL_FIELD_NUMBER;
    hash = (53 * hash) + getAnchorCol();
    hash = (37 * hash) + SNAPSHOT_OBSERVED_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSnapshotObservedAt());
    hash = (37 * hash) + PARSED_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getParsedAt());
    if (getCandidatesCount() > 0) {
      hash = (37 * hash) + CANDIDATES_FIELD_NUMBER;
      hash = (53 * hash) + getCandidatesList().hashCode();
    }
    if (getCellsCount() > 0) {
      hash = (37 * hash) + CELLS_FIELD_NUMBER;
      hash = (53 * hash) + getCellsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code teamviewer.v1.BattleMapObservation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:teamviewer.v1.BattleMapObservation)
      fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_BattleMapObservation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_BattleMapObservation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation.class, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation.Builder.class);
    }

    // Construct using fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      dimension_ = "";
      mapSize_ = 0;
      anchorRow_ = 0;
      anchorCol_ = 0;
      snapshotObservedAt_ = 0L;
      parsedAt_ = 0L;
      if (candidatesBuilder_ == null) {
        candidates_ = java.util.Collections.emptyList();
      } else {
        candidates_ = null;
        candidatesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      if (cellsBuilder_ == null) {
        cells_ = java.util.Collections.emptyList();
      } else {
        cells_ = null;
        cellsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_BattleMapObservation_descriptor;
    }

    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation getDefaultInstanceForType() {
      return fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation.getDefaultInstance();
    }

    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation build() {
      fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation buildPartial() {
      fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation result = new fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation result) {
      if (candidatesBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          candidates_ = java.util.Collections.unmodifiableList(candidates_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.candidates_ = candidates_;
      } else {
        result.candidates_ = candidatesBuilder_.build();
      }
      if (cellsBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0)) {
          cells_ = java.util.Collections.unmodifiableList(cells_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.cells_ = cells_;
      } else {
        result.cells_ = cellsBuilder_.build();
      }
    }

    private void buildPartial0(fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.dimension_ = dimension_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.mapSize_ = mapSize_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.anchorRow_ = anchorRow_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.anchorCol_ = anchorCol_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.snapshotObservedAt_ = snapshotObservedAt_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.parsedAt_ = parsedAt_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation) {
        return mergeFrom((fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation other) {
      if (other == fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation.getDefaultInstance()) return this;
      if (!other.getDimension().isEmpty()) {
        dimension_ = other.dimension_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getMapSize() != 0) {
        setMapSize(other.getMapSize());
      }
      if (other.getAnchorRow() != 0) {
        setAnchorRow(other.getAnchorRow());
      }
      if (other.getAnchorCol() != 0) {
        setAnchorCol(other.getAnchorCol());
      }
      if (other.getSnapshotObservedAt() != 0L) {
        setSnapshotObservedAt(other.getSnapshotObservedAt());
      }
      if (other.getParsedAt() != 0L) {
        setParsedAt(other.getParsedAt());
      }
      if (candidatesBuilder_ == null) {
        if (!other.candidates_.isEmpty()) {
          if (candidates_.isEmpty()) {
            candidates_ = other.candidates_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureCandidatesIsMutable();
            candidates_.addAll(other.candidates_);
          }
          onChanged();
        }
      } else {
        if (!other.candidates_.isEmpty()) {
          if (candidatesBuilder_.isEmpty()) {
            candidatesBuilder_.dispose();
            candidatesBuilder_ = null;
            candidates_ = other.candidates_;
            bitField0_ = (bitField0_ & ~0x00000040);
            candidatesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetCandidatesFieldBuilder() : null;
          } else {
            candidatesBuilder_.addAllMessages(other.candidates_);
          }
        }
      }
      if (cellsBuilder_ == null) {
        if (!other.cells_.isEmpty()) {
          if (cells_.isEmpty()) {
            cells_ = other.cells_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureCellsIsMutable();
            cells_.addAll(other.cells_);
          }
          onChanged();
        }
      } else {
        if (!other.cells_.isEmpty()) {
          if (cellsBuilder_.isEmpty()) {
            cellsBuilder_.dispose();
            cellsBuilder_ = null;
            cells_ = other.cells_;
            bitField0_ = (bitField0_ & ~0x00000080);
            cellsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetCellsFieldBuilder() : null;
          } else {
            cellsBuilder_.addAllMessages(other.cells_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              dimension_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              mapSize_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              anchorRow_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              anchorCol_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              snapshotObservedAt_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              parsedAt_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate m =
                  input.readMessage(
                      fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate.parser(),
                      extensionRegistry);
              if (candidatesBuilder_ == null) {
                ensureCandidatesIsMutable();
                candidates_.add(m);
              } else {
                candidatesBuilder_.addMessage(m);
              }
              break;
            } // case 58
            case 66: {
              fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell m =
                  input.readMessage(
                      fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell.parser(),
                      extensionRegistry);
              if (cellsBuilder_ == null) {
                ensureCellsIsMutable();
                cells_.add(m);
              } else {
                cellsBuilder_.addMessage(m);
              }
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object dimension_ = "";
    /**
     * <code>string dimension = 1 [json_name = "dimension"];</code>
     * @return The dimension.
     */
    public java.lang.String getDimension() {
      java.lang.Object ref = dimension_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dimension_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dimension = 1 [json_name = "dimension"];</code>
     * @return The bytes for dimension.
     */
    public com.google.protobuf.ByteString
        getDimensionBytes() {
      java.lang.Object ref = dimension_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dimension_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dimension = 1 [json_name = "dimension"];</code>
     * @param value The dimension to set.
     * @return This builder for chaining.
     */
    public Builder setDimension(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dimension_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string dimension = 1 [json_name = "dimension"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDimension() {
      dimension_ = getDefaultInstance().getDimension();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string dimension = 1 [json_name = "dimension"];</code>
     * @param value The bytes for dimension to set.
     * @return This builder for chaining.
     */
    public Builder setDimensionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dimension_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int mapSize_ ;
    /**
     * <code>int32 map_size = 2 [json_name = "mapSize"];</code>
     * @return The mapSize.
     */
    @java.lang.Override
    public int getMapSize() {
      return mapSize_;
    }
    /**
     * <code>int32 map_size = 2 [json_name = "mapSize"];</code>
     * @param value The mapSize to set.
     * @return This builder for chaining.
     */
    public Builder setMapSize(int value) {

      mapSize_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 map_size = 2 [json_name = "mapSize"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMapSize() {
      bitField0_ = (bitField0_ & ~0x00000002);
      mapSize_ = 0;
      onChanged();
      return this;
    }

    private int anchorRow_ ;
    /**
     * <code>int32 anchor_row = 3 [json_name = "anchorRow"];</code>
     * @return The anchorRow.
     */
    @java.lang.Override
    public int getAnchorRow() {
      return anchorRow_;
    }
    /**
     * <code>int32 anchor_row = 3 [json_name = "anchorRow"];</code>
     * @param value The anchorRow to set.
     * @return This builder for chaining.
     */
    public Builder setAnchorRow(int value) {

      anchorRow_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 anchor_row = 3 [json_name = "anchorRow"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAnchorRow() {
      bitField0_ = (bitField0_ & ~0x00000004);
      anchorRow_ = 0;
      onChanged();
      return this;
    }

    private int anchorCol_ ;
    /**
     * <code>int32 anchor_col = 4 [json_name = "anchorCol"];</code>
     * @return The anchorCol.
     */
    @java.lang.Override
    public int getAnchorCol() {
      return anchorCol_;
    }
    /**
     * <code>int32 anchor_col = 4 [json_name = "anchorCol"];</code>
     * @param value The anchorCol to set.
     * @return This builder for chaining.
     */
    public Builder setAnchorCol(int value) {

      anchorCol_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 anchor_col = 4 [json_name = "anchorCol"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAnchorCol() {
      bitField0_ = (bitField0_ & ~0x00000008);
      anchorCol_ = 0;
      onChanged();
      return this;
    }

    private long snapshotObservedAt_ ;
    /**
     * <code>int64 snapshot_observed_at = 5 [json_name = "snapshotObservedAt"];</code>
     * @return The snapshotObservedAt.
     */
    @java.lang.Override
    public long getSnapshotObservedAt() {
      return snapshotObservedAt_;
    }
    /**
     * <code>int64 snapshot_observed_at = 5 [json_name = "snapshotObservedAt"];</code>
     * @param value The snapshotObservedAt to set.
     * @return This builder for chaining.
     */
    public Builder setSnapshotObservedAt(long value) {

      snapshotObservedAt_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 snapshot_observed_at = 5 [json_name = "snapshotObservedAt"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSnapshotObservedAt() {
      bitField0_ = (bitField0_ & ~0x00000010);
      snapshotObservedAt_ = 0L;
      onChanged();
      return this;
    }

    private long parsedAt_ ;
    /**
     * <code>int64 parsed_at = 6 [json_name = "parsedAt"];</code>
     * @return The parsedAt.
     */
    @java.lang.Override
    public long getParsedAt() {
      return parsedAt_;
    }
    /**
     * <code>int64 parsed_at = 6 [json_name = "parsedAt"];</code>
     * @param value The parsedAt to set.
     * @return This builder for chaining.
     */
    public Builder setParsedAt(long value) {

      parsedAt_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 parsed_at = 6 [json_name = "parsedAt"];</code>
     * @return This builder for chaining.
     */
    public Builder clearParsedAt() {
      bitField0_ = (bitField0_ & ~0x00000020);
      parsedAt_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate> candidates_ =
      java.util.Collections.emptyList();
    private void ensureCandidatesIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        candidates_ = new java.util.ArrayList<fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate>(candidates_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate.Builder, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidateOrBuilder> candidatesBuilder_;

    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public java.util.List<fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate> getCandidatesList() {
      if (candidatesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(candidates_);
      } else {
        return candidatesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public int getCandidatesCount() {
      if (candidatesBuilder_ == null) {
        return candidates_.size();
      } else {
        return candidatesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate getCandidates(int index) {
      if (candidatesBuilder_ == null) {
        return candidates_.get(index);
      } else {
        return candidatesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public Builder setCandidates(
        int index, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate value) {
      if (candidatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandidatesIsMutable();
        candidates_.set(index, value);
        onChanged();
      } else {
        candidatesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public Builder setCandidates(
        int index, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate.Builder builderForValue) {
      if (candidatesBuilder_ == null) {
        ensureCandidatesIsMutable();
        candidates_.set(index, builderForValue.build());
        onChanged();
      } else {
        candidatesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public Builder addCandidates(fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate value) {
      if (candidatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandidatesIsMutable();
        candidates_.add(value);
        onChanged();
      } else {
        candidatesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public Builder addCandidates(
        int index, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate value) {
      if (candidatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandidatesIsMutable();
        candidates_.add(index, value);
        onChanged();
      } else {
        candidatesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public Builder addCandidates(
        fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate.Builder builderForValue) {
      if (candidatesBuilder_ == null) {
        ensureCandidatesIsMutable();
        candidates_.add(builderForValue.build());
        onChanged();
      } else {
        candidatesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public Builder addCandidates(
        int index, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate.Builder builderForValue) {
      if (candidatesBuilder_ == null) {
        ensureCandidatesIsMutable();
        candidates_.add(index, builderForValue.build());
        onChanged();
      } else {
        candidatesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public Builder addAllCandidates(
        java.lang.Iterable<? extends fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate> values) {
      if (candidatesBuilder_ == null) {
        ensureCandidatesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, candidates_);
        onChanged();
      } else {
        candidatesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public Builder clearCandidates() {
      if (candidatesBuilder_ == null) {
        candidates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        candidatesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public Builder removeCandidates(int index) {
      if (candidatesBuilder_ == null) {
        ensureCandidatesIsMutable();
        candidates_.remove(index);
        onChanged();
      } else {
        candidatesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate.Builder getCandidatesBuilder(
        int index) {
      return internalGetCandidatesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidateOrBuilder getCandidatesOrBuilder(
        int index) {
      if (candidatesBuilder_ == null) {
        return candidates_.get(index);  } else {
        return candidatesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public java.util.List<? extends fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidateOrBuilder> 
         getCandidatesOrBuilderList() {
      if (candidatesBuilder_ != null) {
        return candidatesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(candidates_);
      }
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate.Builder addCandidatesBuilder() {
      return internalGetCandidatesFieldBuilder().addBuilder(
          fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate.getDefaultInstance());
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate.Builder addCandidatesBuilder(
        int index) {
      return internalGetCandidatesFieldBuilder().addBuilder(
          index, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate.getDefaultInstance());
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCandidate candidates = 7 [json_name = "candidates"];</code>
     */
    public java.util.List<fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate.Builder> 
         getCandidatesBuilderList() {
      return internalGetCandidatesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate.Builder, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidateOrBuilder> 
        internalGetCandidatesFieldBuilder() {
      if (candidatesBuilder_ == null) {
        candidatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidate.Builder, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCandidateOrBuilder>(
                candidates_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        candidates_ = null;
      }
      return candidatesBuilder_;
    }

    private java.util.List<fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell> cells_ =
      java.util.Collections.emptyList();
    private void ensureCellsIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        cells_ = new java.util.ArrayList<fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell>(cells_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell.Builder, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCellOrBuilder> cellsBuilder_;

    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public java.util.List<fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell> getCellsList() {
      if (cellsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cells_);
      } else {
        return cellsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public int getCellsCount() {
      if (cellsBuilder_ == null) {
        return cells_.size();
      } else {
        return cellsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell getCells(int index) {
      if (cellsBuilder_ == null) {
        return cells_.get(index);
      } else {
        return cellsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public Builder setCells(
        int index, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell value) {
      if (cellsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCellsIsMutable();
        cells_.set(index, value);
        onChanged();
      } else {
        cellsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public Builder setCells(
        int index, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell.Builder builderForValue) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        cells_.set(index, builderForValue.build());
        onChanged();
      } else {
        cellsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public Builder addCells(fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell value) {
      if (cellsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCellsIsMutable();
        cells_.add(value);
        onChanged();
      } else {
        cellsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public Builder addCells(
        int index, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell value) {
      if (cellsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCellsIsMutable();
        cells_.add(index, value);
        onChanged();
      } else {
        cellsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public Builder addCells(
        fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell.Builder builderForValue) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        cells_.add(builderForValue.build());
        onChanged();
      } else {
        cellsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public Builder addCells(
        int index, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell.Builder builderForValue) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        cells_.add(index, builderForValue.build());
        onChanged();
      } else {
        cellsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public Builder addAllCells(
        java.lang.Iterable<? extends fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell> values) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cells_);
        onChanged();
      } else {
        cellsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public Builder clearCells() {
      if (cellsBuilder_ == null) {
        cells_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        cellsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public Builder removeCells(int index) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        cells_.remove(index);
        onChanged();
      } else {
        cellsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell.Builder getCellsBuilder(
        int index) {
      return internalGetCellsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCellOrBuilder getCellsOrBuilder(
        int index) {
      if (cellsBuilder_ == null) {
        return cells_.get(index);  } else {
        return cellsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public java.util.List<? extends fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCellOrBuilder> 
         getCellsOrBuilderList() {
      if (cellsBuilder_ != null) {
        return cellsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cells_);
      }
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell.Builder addCellsBuilder() {
      return internalGetCellsFieldBuilder().addBuilder(
          fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell.getDefaultInstance());
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell.Builder addCellsBuilder(
        int index) {
      return internalGetCellsFieldBuilder().addBuilder(
          index, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell.getDefaultInstance());
    }
    /**
     * <code>repeated .teamviewer.v1.BattleMapObservationCell cells = 8 [json_name = "cells"];</code>
     */
    public java.util.List<fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell.Builder> 
         getCellsBuilderList() {
      return internalGetCellsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell.Builder, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCellOrBuilder> 
        internalGetCellsFieldBuilder() {
      if (cellsBuilder_ == null) {
        cellsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCell.Builder, fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationCellOrBuilder>(
                cells_,
                ((bitField0_ & 0x00000080) != 0),
                getParentForChildren(),
                isClean());
        cells_ = null;
      }
      return cellsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:teamviewer.v1.BattleMapObservation)
  }

  // @@protoc_insertion_point(class_scope:teamviewer.v1.BattleMapObservation)
  private static final fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation();
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BattleMapObservation>
      PARSER = new com.google.protobuf.AbstractParser<BattleMapObservation>() {
    @java.lang.Override
    public BattleMapObservation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BattleMapObservation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BattleMapObservation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

