// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

@com.google.protobuf.Generated
public interface BattleChunkPatchScopeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teamviewer.v1.BattleChunkPatchScope)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .teamviewer.v1.BattleChunkUpsert upsert = 1 [json_name = "upsert"];</code>
   */
  java.util.List<fun.prof_chen.teamviewer.main_code.network.proto.BattleChunkUpsert> 
      getUpsertList();
  /**
   * <code>repeated .teamviewer.v1.BattleChunkUpsert upsert = 1 [json_name = "upsert"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.BattleChunkUpsert getUpsert(int index);
  /**
   * <code>repeated .teamviewer.v1.BattleChunkUpsert upsert = 1 [json_name = "upsert"];</code>
   */
  int getUpsertCount();
  /**
   * <code>repeated .teamviewer.v1.BattleChunkUpsert upsert = 1 [json_name = "upsert"];</code>
   */
  java.util.List<? extends fun.prof_chen.teamviewer.main_code.network.proto.BattleChunkUpsertOrBuilder> 
      getUpsertOrBuilderList();
  /**
   * <code>repeated .teamviewer.v1.BattleChunkUpsert upsert = 1 [json_name = "upsert"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.BattleChunkUpsertOrBuilder getUpsertOrBuilder(
      int index);

  /**
   * <code>repeated .teamviewer.v1.BattleChunkRef delete = 2 [json_name = "delete"];</code>
   */
  java.util.List<fun.prof_chen.teamviewer.main_code.network.proto.BattleChunkRef> 
      getDeleteList();
  /**
   * <code>repeated .teamviewer.v1.BattleChunkRef delete = 2 [json_name = "delete"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.BattleChunkRef getDelete(int index);
  /**
   * <code>repeated .teamviewer.v1.BattleChunkRef delete = 2 [json_name = "delete"];</code>
   */
  int getDeleteCount();
  /**
   * <code>repeated .teamviewer.v1.BattleChunkRef delete = 2 [json_name = "delete"];</code>
   */
  java.util.List<? extends fun.prof_chen.teamviewer.main_code.network.proto.BattleChunkRefOrBuilder> 
      getDeleteOrBuilderList();
  /**
   * <code>repeated .teamviewer.v1.BattleChunkRef delete = 2 [json_name = "delete"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.BattleChunkRefOrBuilder getDeleteOrBuilder(
      int index);
}
