// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

@com.google.protobuf.Generated
public interface BattleChunkDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teamviewer.v1.BattleChunkData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 chunk_x = 1 [json_name = "chunkX"];</code>
   * @return The chunkX.
   */
  int getChunkX();

  /**
   * <code>int32 chunk_z = 2 [json_name = "chunkZ"];</code>
   * @return The chunkZ.
   */
  int getChunkZ();

  /**
   * <code>string dimension = 3 [json_name = "dimension"];</code>
   * @return The dimension.
   */
  java.lang.String getDimension();
  /**
   * <code>string dimension = 3 [json_name = "dimension"];</code>
   * @return The bytes for dimension.
   */
  com.google.protobuf.ByteString
      getDimensionBytes();

  /**
   * <code>optional string symbol = 4 [json_name = "symbol"];</code>
   * @return Whether the symbol field is set.
   */
  boolean hasSymbol();
  /**
   * <code>optional string symbol = 4 [json_name = "symbol"];</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>optional string symbol = 4 [json_name = "symbol"];</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>optional string marker_type = 5 [json_name = "markerType"];</code>
   * @return Whether the markerType field is set.
   */
  boolean hasMarkerType();
  /**
   * <code>optional string marker_type = 5 [json_name = "markerType"];</code>
   * @return The markerType.
   */
  java.lang.String getMarkerType();
  /**
   * <code>optional string marker_type = 5 [json_name = "markerType"];</code>
   * @return The bytes for markerType.
   */
  com.google.protobuf.ByteString
      getMarkerTypeBytes();

  /**
   * <code>string color_raw = 6 [json_name = "colorRaw"];</code>
   * @return The colorRaw.
   */
  java.lang.String getColorRaw();
  /**
   * <code>string color_raw = 6 [json_name = "colorRaw"];</code>
   * @return The bytes for colorRaw.
   */
  com.google.protobuf.ByteString
      getColorRawBytes();

  /**
   * <code>optional string color_note = 7 [json_name = "colorNote"];</code>
   * @return Whether the colorNote field is set.
   */
  boolean hasColorNote();
  /**
   * <code>optional string color_note = 7 [json_name = "colorNote"];</code>
   * @return The colorNote.
   */
  java.lang.String getColorNote();
  /**
   * <code>optional string color_note = 7 [json_name = "colorNote"];</code>
   * @return The bytes for colorNote.
   */
  com.google.protobuf.ByteString
      getColorNoteBytes();

  /**
   * <code>optional int64 observed_at = 8 [json_name = "observedAt"];</code>
   * @return Whether the observedAt field is set.
   */
  boolean hasObservedAt();
  /**
   * <code>optional int64 observed_at = 8 [json_name = "observedAt"];</code>
   * @return The observedAt.
   */
  long getObservedAt();

  /**
   * <code>optional int64 position_sampled_at = 9 [json_name = "positionSampledAt"];</code>
   * @return Whether the positionSampledAt field is set.
   */
  boolean hasPositionSampledAt();
  /**
   * <code>optional int64 position_sampled_at = 9 [json_name = "positionSampledAt"];</code>
   * @return The positionSampledAt.
   */
  long getPositionSampledAt();

  /**
   * <code>optional string alignment_source = 10 [json_name = "alignmentSource"];</code>
   * @return Whether the alignmentSource field is set.
   */
  boolean hasAlignmentSource();
  /**
   * <code>optional string alignment_source = 10 [json_name = "alignmentSource"];</code>
   * @return The alignmentSource.
   */
  java.lang.String getAlignmentSource();
  /**
   * <code>optional string alignment_source = 10 [json_name = "alignmentSource"];</code>
   * @return The bytes for alignmentSource.
   */
  com.google.protobuf.ByteString
      getAlignmentSourceBytes();

  /**
   * <code>optional string reporter_id = 11 [json_name = "reporterId"];</code>
   * @return Whether the reporterId field is set.
   */
  boolean hasReporterId();
  /**
   * <code>optional string reporter_id = 11 [json_name = "reporterId"];</code>
   * @return The reporterId.
   */
  java.lang.String getReporterId();
  /**
   * <code>optional string reporter_id = 11 [json_name = "reporterId"];</code>
   * @return The bytes for reporterId.
   */
  com.google.protobuf.ByteString
      getReporterIdBytes();

  /**
   * <code>optional string room_code = 12 [json_name = "roomCode"];</code>
   * @return Whether the roomCode field is set.
   */
  boolean hasRoomCode();
  /**
   * <code>optional string room_code = 12 [json_name = "roomCode"];</code>
   * @return The roomCode.
   */
  java.lang.String getRoomCode();
  /**
   * <code>optional string room_code = 12 [json_name = "roomCode"];</code>
   * @return The bytes for roomCode.
   */
  com.google.protobuf.ByteString
      getRoomCodeBytes();
}
