// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

/**
 * Protobuf type {@code teamviewer.v1.CommandTacticalWaypointSet}
 */
@com.google.protobuf.Generated
public final class CommandTacticalWaypointSet extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:teamviewer.v1.CommandTacticalWaypointSet)
    CommandTacticalWaypointSetOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "CommandTacticalWaypointSet");
  }
  // Use CommandTacticalWaypointSet.newBuilder() to construct.
  private CommandTacticalWaypointSet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CommandTacticalWaypointSet() {
    waypointId_ = "";
    label_ = "";
    dimension_ = "";
    tacticalType_ = "";
    color_ = "";
    roomCode_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_CommandTacticalWaypointSet_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_CommandTacticalWaypointSet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_CommandTacticalWaypointSet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet.class, fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet.Builder.class);
  }

  private int bitField0_;
  public static final int WAYPOINT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object waypointId_ = "";
  /**
   * <code>optional string waypoint_id = 1 [json_name = "waypointId"];</code>
   * @return Whether the waypointId field is set.
   */
  @java.lang.Override
  public boolean hasWaypointId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string waypoint_id = 1 [json_name = "waypointId"];</code>
   * @return The waypointId.
   */
  @java.lang.Override
  public java.lang.String getWaypointId() {
    java.lang.Object ref = waypointId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      waypointId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string waypoint_id = 1 [json_name = "waypointId"];</code>
   * @return The bytes for waypointId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWaypointIdBytes() {
    java.lang.Object ref = waypointId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      waypointId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int X_FIELD_NUMBER = 2;
  private double x_ = 0D;
  /**
   * <code>optional double x = 2 [json_name = "x"];</code>
   * @return Whether the x field is set.
   */
  @java.lang.Override
  public boolean hasX() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional double x = 2 [json_name = "x"];</code>
   * @return The x.
   */
  @java.lang.Override
  public double getX() {
    return x_;
  }

  public static final int Z_FIELD_NUMBER = 3;
  private double z_ = 0D;
  /**
   * <code>optional double z = 3 [json_name = "z"];</code>
   * @return Whether the z field is set.
   */
  @java.lang.Override
  public boolean hasZ() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional double z = 3 [json_name = "z"];</code>
   * @return The z.
   */
  @java.lang.Override
  public double getZ() {
    return z_;
  }

  public static final int LABEL_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object label_ = "";
  /**
   * <code>optional string label = 4 [json_name = "label"];</code>
   * @return Whether the label field is set.
   */
  @java.lang.Override
  public boolean hasLabel() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string label = 4 [json_name = "label"];</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      label_ = s;
      return s;
    }
  }
  /**
   * <code>optional string label = 4 [json_name = "label"];</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      label_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIMENSION_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dimension_ = "";
  /**
   * <code>optional string dimension = 5 [json_name = "dimension"];</code>
   * @return Whether the dimension field is set.
   */
  @java.lang.Override
  public boolean hasDimension() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string dimension = 5 [json_name = "dimension"];</code>
   * @return The dimension.
   */
  @java.lang.Override
  public java.lang.String getDimension() {
    java.lang.Object ref = dimension_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dimension_ = s;
      return s;
    }
  }
  /**
   * <code>optional string dimension = 5 [json_name = "dimension"];</code>
   * @return The bytes for dimension.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDimensionBytes() {
    java.lang.Object ref = dimension_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dimension_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TACTICAL_TYPE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tacticalType_ = "";
  /**
   * <code>optional string tactical_type = 6 [json_name = "tacticalType"];</code>
   * @return Whether the tacticalType field is set.
   */
  @java.lang.Override
  public boolean hasTacticalType() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string tactical_type = 6 [json_name = "tacticalType"];</code>
   * @return The tacticalType.
   */
  @java.lang.Override
  public java.lang.String getTacticalType() {
    java.lang.Object ref = tacticalType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tacticalType_ = s;
      return s;
    }
  }
  /**
   * <code>optional string tactical_type = 6 [json_name = "tacticalType"];</code>
   * @return The bytes for tacticalType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTacticalTypeBytes() {
    java.lang.Object ref = tacticalType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tacticalType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERMANENT_FIELD_NUMBER = 7;
  private boolean permanent_ = false;
  /**
   * <code>optional bool permanent = 7 [json_name = "permanent"];</code>
   * @return Whether the permanent field is set.
   */
  @java.lang.Override
  public boolean hasPermanent() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional bool permanent = 7 [json_name = "permanent"];</code>
   * @return The permanent.
   */
  @java.lang.Override
  public boolean getPermanent() {
    return permanent_;
  }

  public static final int TTL_SECONDS_FIELD_NUMBER = 8;
  private int ttlSeconds_ = 0;
  /**
   * <code>optional int32 ttl_seconds = 8 [json_name = "ttlSeconds"];</code>
   * @return Whether the ttlSeconds field is set.
   */
  @java.lang.Override
  public boolean hasTtlSeconds() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional int32 ttl_seconds = 8 [json_name = "ttlSeconds"];</code>
   * @return The ttlSeconds.
   */
  @java.lang.Override
  public int getTtlSeconds() {
    return ttlSeconds_;
  }

  public static final int COLOR_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object color_ = "";
  /**
   * <code>optional string color = 9 [json_name = "color"];</code>
   * @return Whether the color field is set.
   */
  @java.lang.Override
  public boolean hasColor() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional string color = 9 [json_name = "color"];</code>
   * @return The color.
   */
  @java.lang.Override
  public java.lang.String getColor() {
    java.lang.Object ref = color_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      color_ = s;
      return s;
    }
  }
  /**
   * <code>optional string color = 9 [json_name = "color"];</code>
   * @return The bytes for color.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getColorBytes() {
    java.lang.Object ref = color_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      color_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOM_CODE_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object roomCode_ = "";
  /**
   * <code>optional string room_code = 10 [json_name = "roomCode"];</code>
   * @return Whether the roomCode field is set.
   */
  @java.lang.Override
  public boolean hasRoomCode() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <code>optional string room_code = 10 [json_name = "roomCode"];</code>
   * @return The roomCode.
   */
  @java.lang.Override
  public java.lang.String getRoomCode() {
    java.lang.Object ref = roomCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roomCode_ = s;
      return s;
    }
  }
  /**
   * <code>optional string room_code = 10 [json_name = "roomCode"];</code>
   * @return The bytes for roomCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoomCodeBytes() {
    java.lang.Object ref = roomCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roomCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, waypointId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeDouble(2, x_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeDouble(3, z_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, label_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, dimension_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, tacticalType_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeBool(7, permanent_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeInt32(8, ttlSeconds_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, color_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, roomCode_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, waypointId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, x_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, z_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, label_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, dimension_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, tacticalType_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, permanent_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, ttlSeconds_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, color_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, roomCode_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet)) {
      return super.equals(obj);
    }
    fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet other = (fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet) obj;

    if (hasWaypointId() != other.hasWaypointId()) return false;
    if (hasWaypointId()) {
      if (!getWaypointId()
          .equals(other.getWaypointId())) return false;
    }
    if (hasX() != other.hasX()) return false;
    if (hasX()) {
      if (java.lang.Double.doubleToLongBits(getX())
          != java.lang.Double.doubleToLongBits(
              other.getX())) return false;
    }
    if (hasZ() != other.hasZ()) return false;
    if (hasZ()) {
      if (java.lang.Double.doubleToLongBits(getZ())
          != java.lang.Double.doubleToLongBits(
              other.getZ())) return false;
    }
    if (hasLabel() != other.hasLabel()) return false;
    if (hasLabel()) {
      if (!getLabel()
          .equals(other.getLabel())) return false;
    }
    if (hasDimension() != other.hasDimension()) return false;
    if (hasDimension()) {
      if (!getDimension()
          .equals(other.getDimension())) return false;
    }
    if (hasTacticalType() != other.hasTacticalType()) return false;
    if (hasTacticalType()) {
      if (!getTacticalType()
          .equals(other.getTacticalType())) return false;
    }
    if (hasPermanent() != other.hasPermanent()) return false;
    if (hasPermanent()) {
      if (getPermanent()
          != other.getPermanent()) return false;
    }
    if (hasTtlSeconds() != other.hasTtlSeconds()) return false;
    if (hasTtlSeconds()) {
      if (getTtlSeconds()
          != other.getTtlSeconds()) return false;
    }
    if (hasColor() != other.hasColor()) return false;
    if (hasColor()) {
      if (!getColor()
          .equals(other.getColor())) return false;
    }
    if (hasRoomCode() != other.hasRoomCode()) return false;
    if (hasRoomCode()) {
      if (!getRoomCode()
          .equals(other.getRoomCode())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasWaypointId()) {
      hash = (37 * hash) + WAYPOINT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getWaypointId().hashCode();
    }
    if (hasX()) {
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getX()));
    }
    if (hasZ()) {
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getZ()));
    }
    if (hasLabel()) {
      hash = (37 * hash) + LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getLabel().hashCode();
    }
    if (hasDimension()) {
      hash = (37 * hash) + DIMENSION_FIELD_NUMBER;
      hash = (53 * hash) + getDimension().hashCode();
    }
    if (hasTacticalType()) {
      hash = (37 * hash) + TACTICAL_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getTacticalType().hashCode();
    }
    if (hasPermanent()) {
      hash = (37 * hash) + PERMANENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPermanent());
    }
    if (hasTtlSeconds()) {
      hash = (37 * hash) + TTL_SECONDS_FIELD_NUMBER;
      hash = (53 * hash) + getTtlSeconds();
    }
    if (hasColor()) {
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor().hashCode();
    }
    if (hasRoomCode()) {
      hash = (37 * hash) + ROOM_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getRoomCode().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code teamviewer.v1.CommandTacticalWaypointSet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:teamviewer.v1.CommandTacticalWaypointSet)
      fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_CommandTacticalWaypointSet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_CommandTacticalWaypointSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet.class, fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet.Builder.class);
    }

    // Construct using fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      waypointId_ = "";
      x_ = 0D;
      z_ = 0D;
      label_ = "";
      dimension_ = "";
      tacticalType_ = "";
      permanent_ = false;
      ttlSeconds_ = 0;
      color_ = "";
      roomCode_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_CommandTacticalWaypointSet_descriptor;
    }

    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet getDefaultInstanceForType() {
      return fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet.getDefaultInstance();
    }

    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet build() {
      fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet buildPartial() {
      fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet result = new fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.waypointId_ = waypointId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.x_ = x_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.z_ = z_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.label_ = label_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.dimension_ = dimension_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.tacticalType_ = tacticalType_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.permanent_ = permanent_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.ttlSeconds_ = ttlSeconds_;
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.color_ = color_;
        to_bitField0_ |= 0x00000100;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.roomCode_ = roomCode_;
        to_bitField0_ |= 0x00000200;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet) {
        return mergeFrom((fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet other) {
      if (other == fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet.getDefaultInstance()) return this;
      if (other.hasWaypointId()) {
        waypointId_ = other.waypointId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasX()) {
        setX(other.getX());
      }
      if (other.hasZ()) {
        setZ(other.getZ());
      }
      if (other.hasLabel()) {
        label_ = other.label_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasDimension()) {
        dimension_ = other.dimension_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasTacticalType()) {
        tacticalType_ = other.tacticalType_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.hasPermanent()) {
        setPermanent(other.getPermanent());
      }
      if (other.hasTtlSeconds()) {
        setTtlSeconds(other.getTtlSeconds());
      }
      if (other.hasColor()) {
        color_ = other.color_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (other.hasRoomCode()) {
        roomCode_ = other.roomCode_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              waypointId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 17: {
              x_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              z_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 34: {
              label_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              dimension_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              tacticalType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              permanent_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              ttlSeconds_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              color_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              roomCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object waypointId_ = "";
    /**
     * <code>optional string waypoint_id = 1 [json_name = "waypointId"];</code>
     * @return Whether the waypointId field is set.
     */
    public boolean hasWaypointId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string waypoint_id = 1 [json_name = "waypointId"];</code>
     * @return The waypointId.
     */
    public java.lang.String getWaypointId() {
      java.lang.Object ref = waypointId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        waypointId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string waypoint_id = 1 [json_name = "waypointId"];</code>
     * @return The bytes for waypointId.
     */
    public com.google.protobuf.ByteString
        getWaypointIdBytes() {
      java.lang.Object ref = waypointId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        waypointId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string waypoint_id = 1 [json_name = "waypointId"];</code>
     * @param value The waypointId to set.
     * @return This builder for chaining.
     */
    public Builder setWaypointId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      waypointId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string waypoint_id = 1 [json_name = "waypointId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearWaypointId() {
      waypointId_ = getDefaultInstance().getWaypointId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string waypoint_id = 1 [json_name = "waypointId"];</code>
     * @param value The bytes for waypointId to set.
     * @return This builder for chaining.
     */
    public Builder setWaypointIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      waypointId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private double x_ ;
    /**
     * <code>optional double x = 2 [json_name = "x"];</code>
     * @return Whether the x field is set.
     */
    @java.lang.Override
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional double x = 2 [json_name = "x"];</code>
     * @return The x.
     */
    @java.lang.Override
    public double getX() {
      return x_;
    }
    /**
     * <code>optional double x = 2 [json_name = "x"];</code>
     * @param value The x to set.
     * @return This builder for chaining.
     */
    public Builder setX(double value) {

      x_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional double x = 2 [json_name = "x"];</code>
     * @return This builder for chaining.
     */
    public Builder clearX() {
      bitField0_ = (bitField0_ & ~0x00000002);
      x_ = 0D;
      onChanged();
      return this;
    }

    private double z_ ;
    /**
     * <code>optional double z = 3 [json_name = "z"];</code>
     * @return Whether the z field is set.
     */
    @java.lang.Override
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional double z = 3 [json_name = "z"];</code>
     * @return The z.
     */
    @java.lang.Override
    public double getZ() {
      return z_;
    }
    /**
     * <code>optional double z = 3 [json_name = "z"];</code>
     * @param value The z to set.
     * @return This builder for chaining.
     */
    public Builder setZ(double value) {

      z_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional double z = 3 [json_name = "z"];</code>
     * @return This builder for chaining.
     */
    public Builder clearZ() {
      bitField0_ = (bitField0_ & ~0x00000004);
      z_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object label_ = "";
    /**
     * <code>optional string label = 4 [json_name = "label"];</code>
     * @return Whether the label field is set.
     */
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string label = 4 [json_name = "label"];</code>
     * @return The label.
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string label = 4 [json_name = "label"];</code>
     * @return The bytes for label.
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string label = 4 [json_name = "label"];</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      label_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string label = 4 [json_name = "label"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      label_ = getDefaultInstance().getLabel();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string label = 4 [json_name = "label"];</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      label_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object dimension_ = "";
    /**
     * <code>optional string dimension = 5 [json_name = "dimension"];</code>
     * @return Whether the dimension field is set.
     */
    public boolean hasDimension() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string dimension = 5 [json_name = "dimension"];</code>
     * @return The dimension.
     */
    public java.lang.String getDimension() {
      java.lang.Object ref = dimension_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dimension_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string dimension = 5 [json_name = "dimension"];</code>
     * @return The bytes for dimension.
     */
    public com.google.protobuf.ByteString
        getDimensionBytes() {
      java.lang.Object ref = dimension_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dimension_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string dimension = 5 [json_name = "dimension"];</code>
     * @param value The dimension to set.
     * @return This builder for chaining.
     */
    public Builder setDimension(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dimension_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional string dimension = 5 [json_name = "dimension"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDimension() {
      dimension_ = getDefaultInstance().getDimension();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>optional string dimension = 5 [json_name = "dimension"];</code>
     * @param value The bytes for dimension to set.
     * @return This builder for chaining.
     */
    public Builder setDimensionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dimension_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object tacticalType_ = "";
    /**
     * <code>optional string tactical_type = 6 [json_name = "tacticalType"];</code>
     * @return Whether the tacticalType field is set.
     */
    public boolean hasTacticalType() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string tactical_type = 6 [json_name = "tacticalType"];</code>
     * @return The tacticalType.
     */
    public java.lang.String getTacticalType() {
      java.lang.Object ref = tacticalType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tacticalType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string tactical_type = 6 [json_name = "tacticalType"];</code>
     * @return The bytes for tacticalType.
     */
    public com.google.protobuf.ByteString
        getTacticalTypeBytes() {
      java.lang.Object ref = tacticalType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tacticalType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string tactical_type = 6 [json_name = "tacticalType"];</code>
     * @param value The tacticalType to set.
     * @return This builder for chaining.
     */
    public Builder setTacticalType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tacticalType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional string tactical_type = 6 [json_name = "tacticalType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTacticalType() {
      tacticalType_ = getDefaultInstance().getTacticalType();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>optional string tactical_type = 6 [json_name = "tacticalType"];</code>
     * @param value The bytes for tacticalType to set.
     * @return This builder for chaining.
     */
    public Builder setTacticalTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tacticalType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private boolean permanent_ ;
    /**
     * <code>optional bool permanent = 7 [json_name = "permanent"];</code>
     * @return Whether the permanent field is set.
     */
    @java.lang.Override
    public boolean hasPermanent() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional bool permanent = 7 [json_name = "permanent"];</code>
     * @return The permanent.
     */
    @java.lang.Override
    public boolean getPermanent() {
      return permanent_;
    }
    /**
     * <code>optional bool permanent = 7 [json_name = "permanent"];</code>
     * @param value The permanent to set.
     * @return This builder for chaining.
     */
    public Builder setPermanent(boolean value) {

      permanent_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool permanent = 7 [json_name = "permanent"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPermanent() {
      bitField0_ = (bitField0_ & ~0x00000040);
      permanent_ = false;
      onChanged();
      return this;
    }

    private int ttlSeconds_ ;
    /**
     * <code>optional int32 ttl_seconds = 8 [json_name = "ttlSeconds"];</code>
     * @return Whether the ttlSeconds field is set.
     */
    @java.lang.Override
    public boolean hasTtlSeconds() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional int32 ttl_seconds = 8 [json_name = "ttlSeconds"];</code>
     * @return The ttlSeconds.
     */
    @java.lang.Override
    public int getTtlSeconds() {
      return ttlSeconds_;
    }
    /**
     * <code>optional int32 ttl_seconds = 8 [json_name = "ttlSeconds"];</code>
     * @param value The ttlSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setTtlSeconds(int value) {

      ttlSeconds_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 ttl_seconds = 8 [json_name = "ttlSeconds"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTtlSeconds() {
      bitField0_ = (bitField0_ & ~0x00000080);
      ttlSeconds_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object color_ = "";
    /**
     * <code>optional string color = 9 [json_name = "color"];</code>
     * @return Whether the color field is set.
     */
    public boolean hasColor() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional string color = 9 [json_name = "color"];</code>
     * @return The color.
     */
    public java.lang.String getColor() {
      java.lang.Object ref = color_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        color_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string color = 9 [json_name = "color"];</code>
     * @return The bytes for color.
     */
    public com.google.protobuf.ByteString
        getColorBytes() {
      java.lang.Object ref = color_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string color = 9 [json_name = "color"];</code>
     * @param value The color to set.
     * @return This builder for chaining.
     */
    public Builder setColor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      color_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>optional string color = 9 [json_name = "color"];</code>
     * @return This builder for chaining.
     */
    public Builder clearColor() {
      color_ = getDefaultInstance().getColor();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>optional string color = 9 [json_name = "color"];</code>
     * @param value The bytes for color to set.
     * @return This builder for chaining.
     */
    public Builder setColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      color_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object roomCode_ = "";
    /**
     * <code>optional string room_code = 10 [json_name = "roomCode"];</code>
     * @return Whether the roomCode field is set.
     */
    public boolean hasRoomCode() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional string room_code = 10 [json_name = "roomCode"];</code>
     * @return The roomCode.
     */
    public java.lang.String getRoomCode() {
      java.lang.Object ref = roomCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string room_code = 10 [json_name = "roomCode"];</code>
     * @return The bytes for roomCode.
     */
    public com.google.protobuf.ByteString
        getRoomCodeBytes() {
      java.lang.Object ref = roomCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string room_code = 10 [json_name = "roomCode"];</code>
     * @param value The roomCode to set.
     * @return This builder for chaining.
     */
    public Builder setRoomCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      roomCode_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>optional string room_code = 10 [json_name = "roomCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomCode() {
      roomCode_ = getDefaultInstance().getRoomCode();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>optional string room_code = 10 [json_name = "roomCode"];</code>
     * @param value The bytes for roomCode to set.
     * @return This builder for chaining.
     */
    public Builder setRoomCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      roomCode_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:teamviewer.v1.CommandTacticalWaypointSet)
  }

  // @@protoc_insertion_point(class_scope:teamviewer.v1.CommandTacticalWaypointSet)
  private static final fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet();
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommandTacticalWaypointSet>
      PARSER = new com.google.protobuf.AbstractParser<CommandTacticalWaypointSet>() {
    @java.lang.Override
    public CommandTacticalWaypointSet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CommandTacticalWaypointSet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommandTacticalWaypointSet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

