// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

@com.google.protobuf.Generated
public interface EntitiesReplaceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teamviewer.v1.EntitiesReplace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .teamviewer.v1.EntityData&gt; entities = 1 [json_name = "entities"];</code>
   */
  int getEntitiesCount();
  /**
   * <code>map&lt;string, .teamviewer.v1.EntityData&gt; entities = 1 [json_name = "entities"];</code>
   */
  boolean containsEntities(
      java.lang.String key);
  /**
   * Use {@link #getEntitiesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.EntityData>
  getEntities();
  /**
   * <code>map&lt;string, .teamviewer.v1.EntityData&gt; entities = 1 [json_name = "entities"];</code>
   */
  java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.EntityData>
  getEntitiesMap();
  /**
   * <code>map&lt;string, .teamviewer.v1.EntityData&gt; entities = 1 [json_name = "entities"];</code>
   */
  /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.EntityData getEntitiesOrDefault(
      java.lang.String key,
      /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.EntityData defaultValue);
  /**
   * <code>map&lt;string, .teamviewer.v1.EntityData&gt; entities = 1 [json_name = "entities"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.EntityData getEntitiesOrThrow(
      java.lang.String key);
}
