// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.29.3

package fun.prof_chen.teamviewer.main_code.network.proto;

/**
 * Protobuf type {@code teamviewer.v1.HandshakeRequest}
 */
public final class HandshakeRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:teamviewer.v1.HandshakeRequest)
    HandshakeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      HandshakeRequest.class.getName());
  }
  // Use HandshakeRequest.newBuilder() to construct.
  private HandshakeRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private HandshakeRequest() {
    networkProtocolVersion_ = "";
    minimumCompatibleNetworkProtocolVersion_ = "";
    localProgramVersion_ = "";
    programVersion_ = "";
    roomCode_ = "";
    roomId_ = "";
    submitPlayerId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_HandshakeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_HandshakeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest.class, fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest.Builder.class);
  }

  private int bitField0_;
  public static final int NETWORK_PROTOCOL_VERSION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object networkProtocolVersion_ = "";
  /**
   * <code>string network_protocol_version = 1;</code>
   * @return The networkProtocolVersion.
   */
  @java.lang.Override
  public java.lang.String getNetworkProtocolVersion() {
    java.lang.Object ref = networkProtocolVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      networkProtocolVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string network_protocol_version = 1;</code>
   * @return The bytes for networkProtocolVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNetworkProtocolVersionBytes() {
    java.lang.Object ref = networkProtocolVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      networkProtocolVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MINIMUM_COMPATIBLE_NETWORK_PROTOCOL_VERSION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object minimumCompatibleNetworkProtocolVersion_ = "";
  /**
   * <code>string minimum_compatible_network_protocol_version = 2;</code>
   * @return The minimumCompatibleNetworkProtocolVersion.
   */
  @java.lang.Override
  public java.lang.String getMinimumCompatibleNetworkProtocolVersion() {
    java.lang.Object ref = minimumCompatibleNetworkProtocolVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      minimumCompatibleNetworkProtocolVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string minimum_compatible_network_protocol_version = 2;</code>
   * @return The bytes for minimumCompatibleNetworkProtocolVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMinimumCompatibleNetworkProtocolVersionBytes() {
    java.lang.Object ref = minimumCompatibleNetworkProtocolVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      minimumCompatibleNetworkProtocolVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCAL_PROGRAM_VERSION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object localProgramVersion_ = "";
  /**
   * <code>string local_program_version = 3;</code>
   * @return The localProgramVersion.
   */
  @java.lang.Override
  public java.lang.String getLocalProgramVersion() {
    java.lang.Object ref = localProgramVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      localProgramVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string local_program_version = 3;</code>
   * @return The bytes for localProgramVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocalProgramVersionBytes() {
    java.lang.Object ref = localProgramVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      localProgramVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROGRAM_VERSION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object programVersion_ = "";
  /**
   * <code>optional string program_version = 4;</code>
   * @return Whether the programVersion field is set.
   */
  @java.lang.Override
  public boolean hasProgramVersion() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string program_version = 4;</code>
   * @return The programVersion.
   */
  @java.lang.Override
  public java.lang.String getProgramVersion() {
    java.lang.Object ref = programVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      programVersion_ = s;
      return s;
    }
  }
  /**
   * <code>optional string program_version = 4;</code>
   * @return The bytes for programVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProgramVersionBytes() {
    java.lang.Object ref = programVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      programVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOM_CODE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object roomCode_ = "";
  /**
   * <code>optional string room_code = 5;</code>
   * @return Whether the roomCode field is set.
   */
  @java.lang.Override
  public boolean hasRoomCode() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string room_code = 5;</code>
   * @return The roomCode.
   */
  @java.lang.Override
  public java.lang.String getRoomCode() {
    java.lang.Object ref = roomCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roomCode_ = s;
      return s;
    }
  }
  /**
   * <code>optional string room_code = 5;</code>
   * @return The bytes for roomCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoomCodeBytes() {
    java.lang.Object ref = roomCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roomCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOM_ID_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object roomId_ = "";
  /**
   * <code>optional string room_id = 6;</code>
   * @return Whether the roomId field is set.
   */
  @java.lang.Override
  public boolean hasRoomId() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string room_id = 6;</code>
   * @return The roomId.
   */
  @java.lang.Override
  public java.lang.String getRoomId() {
    java.lang.Object ref = roomId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roomId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string room_id = 6;</code>
   * @return The bytes for roomId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoomIdBytes() {
    java.lang.Object ref = roomId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roomId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBMIT_PLAYER_ID_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object submitPlayerId_ = "";
  /**
   * <code>optional string submit_player_id = 7;</code>
   * @return Whether the submitPlayerId field is set.
   */
  @java.lang.Override
  public boolean hasSubmitPlayerId() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string submit_player_id = 7;</code>
   * @return The submitPlayerId.
   */
  @java.lang.Override
  public java.lang.String getSubmitPlayerId() {
    java.lang.Object ref = submitPlayerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      submitPlayerId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string submit_player_id = 7;</code>
   * @return The bytes for submitPlayerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubmitPlayerIdBytes() {
    java.lang.Object ref = submitPlayerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      submitPlayerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PREFERRED_REPORT_INTERVAL_TICKS_FIELD_NUMBER = 8;
  private int preferredReportIntervalTicks_ = 0;
  /**
   * <code>optional int32 preferred_report_interval_ticks = 8;</code>
   * @return Whether the preferredReportIntervalTicks field is set.
   */
  @java.lang.Override
  public boolean hasPreferredReportIntervalTicks() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int32 preferred_report_interval_ticks = 8;</code>
   * @return The preferredReportIntervalTicks.
   */
  @java.lang.Override
  public int getPreferredReportIntervalTicks() {
    return preferredReportIntervalTicks_;
  }

  public static final int MIN_REPORT_INTERVAL_TICKS_FIELD_NUMBER = 9;
  private int minReportIntervalTicks_ = 0;
  /**
   * <code>optional int32 min_report_interval_ticks = 9;</code>
   * @return Whether the minReportIntervalTicks field is set.
   */
  @java.lang.Override
  public boolean hasMinReportIntervalTicks() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional int32 min_report_interval_ticks = 9;</code>
   * @return The minReportIntervalTicks.
   */
  @java.lang.Override
  public int getMinReportIntervalTicks() {
    return minReportIntervalTicks_;
  }

  public static final int MAX_REPORT_INTERVAL_TICKS_FIELD_NUMBER = 10;
  private int maxReportIntervalTicks_ = 0;
  /**
   * <code>optional int32 max_report_interval_ticks = 10;</code>
   * @return Whether the maxReportIntervalTicks field is set.
   */
  @java.lang.Override
  public boolean hasMaxReportIntervalTicks() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional int32 max_report_interval_ticks = 10;</code>
   * @return The maxReportIntervalTicks.
   */
  @java.lang.Override
  public int getMaxReportIntervalTicks() {
    return maxReportIntervalTicks_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(networkProtocolVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, networkProtocolVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(minimumCompatibleNetworkProtocolVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, minimumCompatibleNetworkProtocolVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(localProgramVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, localProgramVersion_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, programVersion_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, roomCode_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, roomId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, submitPlayerId_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(8, preferredReportIntervalTicks_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeInt32(9, minReportIntervalTicks_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeInt32(10, maxReportIntervalTicks_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(networkProtocolVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, networkProtocolVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(minimumCompatibleNetworkProtocolVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, minimumCompatibleNetworkProtocolVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(localProgramVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, localProgramVersion_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, programVersion_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, roomCode_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, roomId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, submitPlayerId_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, preferredReportIntervalTicks_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, minReportIntervalTicks_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, maxReportIntervalTicks_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest)) {
      return super.equals(obj);
    }
    fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest other = (fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest) obj;

    if (!getNetworkProtocolVersion()
        .equals(other.getNetworkProtocolVersion())) return false;
    if (!getMinimumCompatibleNetworkProtocolVersion()
        .equals(other.getMinimumCompatibleNetworkProtocolVersion())) return false;
    if (!getLocalProgramVersion()
        .equals(other.getLocalProgramVersion())) return false;
    if (hasProgramVersion() != other.hasProgramVersion()) return false;
    if (hasProgramVersion()) {
      if (!getProgramVersion()
          .equals(other.getProgramVersion())) return false;
    }
    if (hasRoomCode() != other.hasRoomCode()) return false;
    if (hasRoomCode()) {
      if (!getRoomCode()
          .equals(other.getRoomCode())) return false;
    }
    if (hasRoomId() != other.hasRoomId()) return false;
    if (hasRoomId()) {
      if (!getRoomId()
          .equals(other.getRoomId())) return false;
    }
    if (hasSubmitPlayerId() != other.hasSubmitPlayerId()) return false;
    if (hasSubmitPlayerId()) {
      if (!getSubmitPlayerId()
          .equals(other.getSubmitPlayerId())) return false;
    }
    if (hasPreferredReportIntervalTicks() != other.hasPreferredReportIntervalTicks()) return false;
    if (hasPreferredReportIntervalTicks()) {
      if (getPreferredReportIntervalTicks()
          != other.getPreferredReportIntervalTicks()) return false;
    }
    if (hasMinReportIntervalTicks() != other.hasMinReportIntervalTicks()) return false;
    if (hasMinReportIntervalTicks()) {
      if (getMinReportIntervalTicks()
          != other.getMinReportIntervalTicks()) return false;
    }
    if (hasMaxReportIntervalTicks() != other.hasMaxReportIntervalTicks()) return false;
    if (hasMaxReportIntervalTicks()) {
      if (getMaxReportIntervalTicks()
          != other.getMaxReportIntervalTicks()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NETWORK_PROTOCOL_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getNetworkProtocolVersion().hashCode();
    hash = (37 * hash) + MINIMUM_COMPATIBLE_NETWORK_PROTOCOL_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getMinimumCompatibleNetworkProtocolVersion().hashCode();
    hash = (37 * hash) + LOCAL_PROGRAM_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getLocalProgramVersion().hashCode();
    if (hasProgramVersion()) {
      hash = (37 * hash) + PROGRAM_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getProgramVersion().hashCode();
    }
    if (hasRoomCode()) {
      hash = (37 * hash) + ROOM_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getRoomCode().hashCode();
    }
    if (hasRoomId()) {
      hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRoomId().hashCode();
    }
    if (hasSubmitPlayerId()) {
      hash = (37 * hash) + SUBMIT_PLAYER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSubmitPlayerId().hashCode();
    }
    if (hasPreferredReportIntervalTicks()) {
      hash = (37 * hash) + PREFERRED_REPORT_INTERVAL_TICKS_FIELD_NUMBER;
      hash = (53 * hash) + getPreferredReportIntervalTicks();
    }
    if (hasMinReportIntervalTicks()) {
      hash = (37 * hash) + MIN_REPORT_INTERVAL_TICKS_FIELD_NUMBER;
      hash = (53 * hash) + getMinReportIntervalTicks();
    }
    if (hasMaxReportIntervalTicks()) {
      hash = (37 * hash) + MAX_REPORT_INTERVAL_TICKS_FIELD_NUMBER;
      hash = (53 * hash) + getMaxReportIntervalTicks();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code teamviewer.v1.HandshakeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:teamviewer.v1.HandshakeRequest)
      fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_HandshakeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_HandshakeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest.class, fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest.Builder.class);
    }

    // Construct using fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      networkProtocolVersion_ = "";
      minimumCompatibleNetworkProtocolVersion_ = "";
      localProgramVersion_ = "";
      programVersion_ = "";
      roomCode_ = "";
      roomId_ = "";
      submitPlayerId_ = "";
      preferredReportIntervalTicks_ = 0;
      minReportIntervalTicks_ = 0;
      maxReportIntervalTicks_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_HandshakeRequest_descriptor;
    }

    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest getDefaultInstanceForType() {
      return fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest build() {
      fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest buildPartial() {
      fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest result = new fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.networkProtocolVersion_ = networkProtocolVersion_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.minimumCompatibleNetworkProtocolVersion_ = minimumCompatibleNetworkProtocolVersion_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.localProgramVersion_ = localProgramVersion_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.programVersion_ = programVersion_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.roomCode_ = roomCode_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.roomId_ = roomId_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.submitPlayerId_ = submitPlayerId_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.preferredReportIntervalTicks_ = preferredReportIntervalTicks_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.minReportIntervalTicks_ = minReportIntervalTicks_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.maxReportIntervalTicks_ = maxReportIntervalTicks_;
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest) {
        return mergeFrom((fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest other) {
      if (other == fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest.getDefaultInstance()) return this;
      if (!other.getNetworkProtocolVersion().isEmpty()) {
        networkProtocolVersion_ = other.networkProtocolVersion_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getMinimumCompatibleNetworkProtocolVersion().isEmpty()) {
        minimumCompatibleNetworkProtocolVersion_ = other.minimumCompatibleNetworkProtocolVersion_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getLocalProgramVersion().isEmpty()) {
        localProgramVersion_ = other.localProgramVersion_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasProgramVersion()) {
        programVersion_ = other.programVersion_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasRoomCode()) {
        roomCode_ = other.roomCode_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasRoomId()) {
        roomId_ = other.roomId_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.hasSubmitPlayerId()) {
        submitPlayerId_ = other.submitPlayerId_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.hasPreferredReportIntervalTicks()) {
        setPreferredReportIntervalTicks(other.getPreferredReportIntervalTicks());
      }
      if (other.hasMinReportIntervalTicks()) {
        setMinReportIntervalTicks(other.getMinReportIntervalTicks());
      }
      if (other.hasMaxReportIntervalTicks()) {
        setMaxReportIntervalTicks(other.getMaxReportIntervalTicks());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              networkProtocolVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              minimumCompatibleNetworkProtocolVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              localProgramVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              programVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              roomCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              roomId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              submitPlayerId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              preferredReportIntervalTicks_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              minReportIntervalTicks_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              maxReportIntervalTicks_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object networkProtocolVersion_ = "";
    /**
     * <code>string network_protocol_version = 1;</code>
     * @return The networkProtocolVersion.
     */
    public java.lang.String getNetworkProtocolVersion() {
      java.lang.Object ref = networkProtocolVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        networkProtocolVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string network_protocol_version = 1;</code>
     * @return The bytes for networkProtocolVersion.
     */
    public com.google.protobuf.ByteString
        getNetworkProtocolVersionBytes() {
      java.lang.Object ref = networkProtocolVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        networkProtocolVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string network_protocol_version = 1;</code>
     * @param value The networkProtocolVersion to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkProtocolVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      networkProtocolVersion_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string network_protocol_version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetworkProtocolVersion() {
      networkProtocolVersion_ = getDefaultInstance().getNetworkProtocolVersion();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string network_protocol_version = 1;</code>
     * @param value The bytes for networkProtocolVersion to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkProtocolVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      networkProtocolVersion_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object minimumCompatibleNetworkProtocolVersion_ = "";
    /**
     * <code>string minimum_compatible_network_protocol_version = 2;</code>
     * @return The minimumCompatibleNetworkProtocolVersion.
     */
    public java.lang.String getMinimumCompatibleNetworkProtocolVersion() {
      java.lang.Object ref = minimumCompatibleNetworkProtocolVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        minimumCompatibleNetworkProtocolVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string minimum_compatible_network_protocol_version = 2;</code>
     * @return The bytes for minimumCompatibleNetworkProtocolVersion.
     */
    public com.google.protobuf.ByteString
        getMinimumCompatibleNetworkProtocolVersionBytes() {
      java.lang.Object ref = minimumCompatibleNetworkProtocolVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        minimumCompatibleNetworkProtocolVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string minimum_compatible_network_protocol_version = 2;</code>
     * @param value The minimumCompatibleNetworkProtocolVersion to set.
     * @return This builder for chaining.
     */
    public Builder setMinimumCompatibleNetworkProtocolVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      minimumCompatibleNetworkProtocolVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string minimum_compatible_network_protocol_version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinimumCompatibleNetworkProtocolVersion() {
      minimumCompatibleNetworkProtocolVersion_ = getDefaultInstance().getMinimumCompatibleNetworkProtocolVersion();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string minimum_compatible_network_protocol_version = 2;</code>
     * @param value The bytes for minimumCompatibleNetworkProtocolVersion to set.
     * @return This builder for chaining.
     */
    public Builder setMinimumCompatibleNetworkProtocolVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      minimumCompatibleNetworkProtocolVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object localProgramVersion_ = "";
    /**
     * <code>string local_program_version = 3;</code>
     * @return The localProgramVersion.
     */
    public java.lang.String getLocalProgramVersion() {
      java.lang.Object ref = localProgramVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        localProgramVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string local_program_version = 3;</code>
     * @return The bytes for localProgramVersion.
     */
    public com.google.protobuf.ByteString
        getLocalProgramVersionBytes() {
      java.lang.Object ref = localProgramVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localProgramVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string local_program_version = 3;</code>
     * @param value The localProgramVersion to set.
     * @return This builder for chaining.
     */
    public Builder setLocalProgramVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      localProgramVersion_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string local_program_version = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocalProgramVersion() {
      localProgramVersion_ = getDefaultInstance().getLocalProgramVersion();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string local_program_version = 3;</code>
     * @param value The bytes for localProgramVersion to set.
     * @return This builder for chaining.
     */
    public Builder setLocalProgramVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      localProgramVersion_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object programVersion_ = "";
    /**
     * <code>optional string program_version = 4;</code>
     * @return Whether the programVersion field is set.
     */
    public boolean hasProgramVersion() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string program_version = 4;</code>
     * @return The programVersion.
     */
    public java.lang.String getProgramVersion() {
      java.lang.Object ref = programVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        programVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string program_version = 4;</code>
     * @return The bytes for programVersion.
     */
    public com.google.protobuf.ByteString
        getProgramVersionBytes() {
      java.lang.Object ref = programVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        programVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string program_version = 4;</code>
     * @param value The programVersion to set.
     * @return This builder for chaining.
     */
    public Builder setProgramVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      programVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string program_version = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearProgramVersion() {
      programVersion_ = getDefaultInstance().getProgramVersion();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string program_version = 4;</code>
     * @param value The bytes for programVersion to set.
     * @return This builder for chaining.
     */
    public Builder setProgramVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      programVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object roomCode_ = "";
    /**
     * <code>optional string room_code = 5;</code>
     * @return Whether the roomCode field is set.
     */
    public boolean hasRoomCode() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string room_code = 5;</code>
     * @return The roomCode.
     */
    public java.lang.String getRoomCode() {
      java.lang.Object ref = roomCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string room_code = 5;</code>
     * @return The bytes for roomCode.
     */
    public com.google.protobuf.ByteString
        getRoomCodeBytes() {
      java.lang.Object ref = roomCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string room_code = 5;</code>
     * @param value The roomCode to set.
     * @return This builder for chaining.
     */
    public Builder setRoomCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      roomCode_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional string room_code = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomCode() {
      roomCode_ = getDefaultInstance().getRoomCode();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>optional string room_code = 5;</code>
     * @param value The bytes for roomCode to set.
     * @return This builder for chaining.
     */
    public Builder setRoomCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      roomCode_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object roomId_ = "";
    /**
     * <code>optional string room_id = 6;</code>
     * @return Whether the roomId field is set.
     */
    public boolean hasRoomId() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string room_id = 6;</code>
     * @return The roomId.
     */
    public java.lang.String getRoomId() {
      java.lang.Object ref = roomId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string room_id = 6;</code>
     * @return The bytes for roomId.
     */
    public com.google.protobuf.ByteString
        getRoomIdBytes() {
      java.lang.Object ref = roomId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string room_id = 6;</code>
     * @param value The roomId to set.
     * @return This builder for chaining.
     */
    public Builder setRoomId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      roomId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional string room_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomId() {
      roomId_ = getDefaultInstance().getRoomId();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>optional string room_id = 6;</code>
     * @param value The bytes for roomId to set.
     * @return This builder for chaining.
     */
    public Builder setRoomIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      roomId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object submitPlayerId_ = "";
    /**
     * <code>optional string submit_player_id = 7;</code>
     * @return Whether the submitPlayerId field is set.
     */
    public boolean hasSubmitPlayerId() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string submit_player_id = 7;</code>
     * @return The submitPlayerId.
     */
    public java.lang.String getSubmitPlayerId() {
      java.lang.Object ref = submitPlayerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        submitPlayerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string submit_player_id = 7;</code>
     * @return The bytes for submitPlayerId.
     */
    public com.google.protobuf.ByteString
        getSubmitPlayerIdBytes() {
      java.lang.Object ref = submitPlayerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        submitPlayerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string submit_player_id = 7;</code>
     * @param value The submitPlayerId to set.
     * @return This builder for chaining.
     */
    public Builder setSubmitPlayerId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      submitPlayerId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional string submit_player_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubmitPlayerId() {
      submitPlayerId_ = getDefaultInstance().getSubmitPlayerId();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>optional string submit_player_id = 7;</code>
     * @param value The bytes for submitPlayerId to set.
     * @return This builder for chaining.
     */
    public Builder setSubmitPlayerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      submitPlayerId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private int preferredReportIntervalTicks_ ;
    /**
     * <code>optional int32 preferred_report_interval_ticks = 8;</code>
     * @return Whether the preferredReportIntervalTicks field is set.
     */
    @java.lang.Override
    public boolean hasPreferredReportIntervalTicks() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional int32 preferred_report_interval_ticks = 8;</code>
     * @return The preferredReportIntervalTicks.
     */
    @java.lang.Override
    public int getPreferredReportIntervalTicks() {
      return preferredReportIntervalTicks_;
    }
    /**
     * <code>optional int32 preferred_report_interval_ticks = 8;</code>
     * @param value The preferredReportIntervalTicks to set.
     * @return This builder for chaining.
     */
    public Builder setPreferredReportIntervalTicks(int value) {

      preferredReportIntervalTicks_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 preferred_report_interval_ticks = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPreferredReportIntervalTicks() {
      bitField0_ = (bitField0_ & ~0x00000080);
      preferredReportIntervalTicks_ = 0;
      onChanged();
      return this;
    }

    private int minReportIntervalTicks_ ;
    /**
     * <code>optional int32 min_report_interval_ticks = 9;</code>
     * @return Whether the minReportIntervalTicks field is set.
     */
    @java.lang.Override
    public boolean hasMinReportIntervalTicks() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional int32 min_report_interval_ticks = 9;</code>
     * @return The minReportIntervalTicks.
     */
    @java.lang.Override
    public int getMinReportIntervalTicks() {
      return minReportIntervalTicks_;
    }
    /**
     * <code>optional int32 min_report_interval_ticks = 9;</code>
     * @param value The minReportIntervalTicks to set.
     * @return This builder for chaining.
     */
    public Builder setMinReportIntervalTicks(int value) {

      minReportIntervalTicks_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 min_report_interval_ticks = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinReportIntervalTicks() {
      bitField0_ = (bitField0_ & ~0x00000100);
      minReportIntervalTicks_ = 0;
      onChanged();
      return this;
    }

    private int maxReportIntervalTicks_ ;
    /**
     * <code>optional int32 max_report_interval_ticks = 10;</code>
     * @return Whether the maxReportIntervalTicks field is set.
     */
    @java.lang.Override
    public boolean hasMaxReportIntervalTicks() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional int32 max_report_interval_ticks = 10;</code>
     * @return The maxReportIntervalTicks.
     */
    @java.lang.Override
    public int getMaxReportIntervalTicks() {
      return maxReportIntervalTicks_;
    }
    /**
     * <code>optional int32 max_report_interval_ticks = 10;</code>
     * @param value The maxReportIntervalTicks to set.
     * @return This builder for chaining.
     */
    public Builder setMaxReportIntervalTicks(int value) {

      maxReportIntervalTicks_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 max_report_interval_ticks = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxReportIntervalTicks() {
      bitField0_ = (bitField0_ & ~0x00000200);
      maxReportIntervalTicks_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:teamviewer.v1.HandshakeRequest)
  }

  // @@protoc_insertion_point(class_scope:teamviewer.v1.HandshakeRequest)
  private static final fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest();
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HandshakeRequest>
      PARSER = new com.google.protobuf.AbstractParser<HandshakeRequest>() {
    @java.lang.Override
    public HandshakeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HandshakeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HandshakeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.HandshakeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

