// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

@com.google.protobuf.Generated
public interface PlayersReplaceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teamviewer.v1.PlayersReplace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
   */
  int getPlayersCount();
  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
   */
  boolean containsPlayers(
      java.lang.String key);
  /**
   * Use {@link #getPlayersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData>
  getPlayers();
  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
   */
  java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData>
  getPlayersMap();
  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
   */
  /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.PlayerData getPlayersOrDefault(
      java.lang.String key,
      /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.PlayerData defaultValue);
  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.PlayerData getPlayersOrThrow(
      java.lang.String key);
}
