// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

@com.google.protobuf.Generated
public interface PlayerHandshakeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teamviewer.v1.PlayerHandshakeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string network_protocol_version = 1 [json_name = "networkProtocolVersion"];</code>
   * @return The networkProtocolVersion.
   */
  java.lang.String getNetworkProtocolVersion();
  /**
   * <code>string network_protocol_version = 1 [json_name = "networkProtocolVersion"];</code>
   * @return The bytes for networkProtocolVersion.
   */
  com.google.protobuf.ByteString
      getNetworkProtocolVersionBytes();

  /**
   * <code>string minimum_compatible_network_protocol_version = 2 [json_name = "minimumCompatibleNetworkProtocolVersion"];</code>
   * @return The minimumCompatibleNetworkProtocolVersion.
   */
  java.lang.String getMinimumCompatibleNetworkProtocolVersion();
  /**
   * <code>string minimum_compatible_network_protocol_version = 2 [json_name = "minimumCompatibleNetworkProtocolVersion"];</code>
   * @return The bytes for minimumCompatibleNetworkProtocolVersion.
   */
  com.google.protobuf.ByteString
      getMinimumCompatibleNetworkProtocolVersionBytes();

  /**
   * <code>string local_program_version = 3 [json_name = "localProgramVersion"];</code>
   * @return The localProgramVersion.
   */
  java.lang.String getLocalProgramVersion();
  /**
   * <code>string local_program_version = 3 [json_name = "localProgramVersion"];</code>
   * @return The bytes for localProgramVersion.
   */
  com.google.protobuf.ByteString
      getLocalProgramVersionBytes();

  /**
   * <code>string submit_player_id = 4 [json_name = "submitPlayerId"];</code>
   * @return The submitPlayerId.
   */
  java.lang.String getSubmitPlayerId();
  /**
   * <code>string submit_player_id = 4 [json_name = "submitPlayerId"];</code>
   * @return The bytes for submitPlayerId.
   */
  com.google.protobuf.ByteString
      getSubmitPlayerIdBytes();

  /**
   * <code>optional string room_code = 5 [json_name = "roomCode"];</code>
   * @return Whether the roomCode field is set.
   */
  boolean hasRoomCode();
  /**
   * <code>optional string room_code = 5 [json_name = "roomCode"];</code>
   * @return The roomCode.
   */
  java.lang.String getRoomCode();
  /**
   * <code>optional string room_code = 5 [json_name = "roomCode"];</code>
   * @return The bytes for roomCode.
   */
  com.google.protobuf.ByteString
      getRoomCodeBytes();

  /**
   * <code>optional int32 preferred_report_interval_ticks = 6 [json_name = "preferredReportIntervalTicks"];</code>
   * @return Whether the preferredReportIntervalTicks field is set.
   */
  boolean hasPreferredReportIntervalTicks();
  /**
   * <code>optional int32 preferred_report_interval_ticks = 6 [json_name = "preferredReportIntervalTicks"];</code>
   * @return The preferredReportIntervalTicks.
   */
  int getPreferredReportIntervalTicks();

  /**
   * <code>optional int32 min_report_interval_ticks = 7 [json_name = "minReportIntervalTicks"];</code>
   * @return Whether the minReportIntervalTicks field is set.
   */
  boolean hasMinReportIntervalTicks();
  /**
   * <code>optional int32 min_report_interval_ticks = 7 [json_name = "minReportIntervalTicks"];</code>
   * @return The minReportIntervalTicks.
   */
  int getMinReportIntervalTicks();

  /**
   * <code>optional int32 max_report_interval_ticks = 8 [json_name = "maxReportIntervalTicks"];</code>
   * @return Whether the maxReportIntervalTicks field is set.
   */
  boolean hasMaxReportIntervalTicks();
  /**
   * <code>optional int32 max_report_interval_ticks = 8 [json_name = "maxReportIntervalTicks"];</code>
   * @return The maxReportIntervalTicks.
   */
  int getMaxReportIntervalTicks();
}
