// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.29.3

package fun.prof_chen.teamviewer.main_code.network.proto;

public interface PlayerMarkUpsertOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teamviewer.v1.PlayerMarkUpsert)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.teamviewer.v1.PlayerMark data = 2;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.teamviewer.v1.PlayerMark data = 2;</code>
   * @return The data.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.PlayerMark getData();
  /**
   * <code>.teamviewer.v1.PlayerMark data = 2;</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.PlayerMarkOrBuilder getDataOrBuilder();
}
