// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

@com.google.protobuf.Generated
public interface PlayerReportBundleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teamviewer.v1.PlayerReportBundle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string submit_player_id = 1 [json_name = "submitPlayerId"];</code>
   * @return The submitPlayerId.
   */
  java.lang.String getSubmitPlayerId();
  /**
   * <code>string submit_player_id = 1 [json_name = "submitPlayerId"];</code>
   * @return The bytes for submitPlayerId.
   */
  com.google.protobuf.ByteString
      getSubmitPlayerIdBytes();

  /**
   * <code>optional .teamviewer.v1.PlayersReplace players_replace = 10 [json_name = "playersReplace"];</code>
   * @return Whether the playersReplace field is set.
   */
  boolean hasPlayersReplace();
  /**
   * <code>optional .teamviewer.v1.PlayersReplace players_replace = 10 [json_name = "playersReplace"];</code>
   * @return The playersReplace.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace getPlayersReplace();
  /**
   * <code>optional .teamviewer.v1.PlayersReplace players_replace = 10 [json_name = "playersReplace"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplaceOrBuilder getPlayersReplaceOrBuilder();

  /**
   * <code>optional .teamviewer.v1.PlayerPatchScope players_patch = 11 [json_name = "playersPatch"];</code>
   * @return Whether the playersPatch field is set.
   */
  boolean hasPlayersPatch();
  /**
   * <code>optional .teamviewer.v1.PlayerPatchScope players_patch = 11 [json_name = "playersPatch"];</code>
   * @return The playersPatch.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.PlayerPatchScope getPlayersPatch();
  /**
   * <code>optional .teamviewer.v1.PlayerPatchScope players_patch = 11 [json_name = "playersPatch"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.PlayerPatchScopeOrBuilder getPlayersPatchOrBuilder();

  /**
   * <code>optional .teamviewer.v1.EntitiesReplace entities_replace = 12 [json_name = "entitiesReplace"];</code>
   * @return Whether the entitiesReplace field is set.
   */
  boolean hasEntitiesReplace();
  /**
   * <code>optional .teamviewer.v1.EntitiesReplace entities_replace = 12 [json_name = "entitiesReplace"];</code>
   * @return The entitiesReplace.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.EntitiesReplace getEntitiesReplace();
  /**
   * <code>optional .teamviewer.v1.EntitiesReplace entities_replace = 12 [json_name = "entitiesReplace"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.EntitiesReplaceOrBuilder getEntitiesReplaceOrBuilder();

  /**
   * <code>optional .teamviewer.v1.EntityPatchScope entities_patch = 13 [json_name = "entitiesPatch"];</code>
   * @return Whether the entitiesPatch field is set.
   */
  boolean hasEntitiesPatch();
  /**
   * <code>optional .teamviewer.v1.EntityPatchScope entities_patch = 13 [json_name = "entitiesPatch"];</code>
   * @return The entitiesPatch.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.EntityPatchScope getEntitiesPatch();
  /**
   * <code>optional .teamviewer.v1.EntityPatchScope entities_patch = 13 [json_name = "entitiesPatch"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.EntityPatchScopeOrBuilder getEntitiesPatchOrBuilder();

  /**
   * <code>optional .teamviewer.v1.WaypointsReplace waypoints_replace = 14 [json_name = "waypointsReplace"];</code>
   * @return Whether the waypointsReplace field is set.
   */
  boolean hasWaypointsReplace();
  /**
   * <code>optional .teamviewer.v1.WaypointsReplace waypoints_replace = 14 [json_name = "waypointsReplace"];</code>
   * @return The waypointsReplace.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.WaypointsReplace getWaypointsReplace();
  /**
   * <code>optional .teamviewer.v1.WaypointsReplace waypoints_replace = 14 [json_name = "waypointsReplace"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.WaypointsReplaceOrBuilder getWaypointsReplaceOrBuilder();

  /**
   * <code>optional .teamviewer.v1.WaypointPatchScope waypoints_patch = 15 [json_name = "waypointsPatch"];</code>
   * @return Whether the waypointsPatch field is set.
   */
  boolean hasWaypointsPatch();
  /**
   * <code>optional .teamviewer.v1.WaypointPatchScope waypoints_patch = 15 [json_name = "waypointsPatch"];</code>
   * @return The waypointsPatch.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.WaypointPatchScope getWaypointsPatch();
  /**
   * <code>optional .teamviewer.v1.WaypointPatchScope waypoints_patch = 15 [json_name = "waypointsPatch"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.WaypointPatchScopeOrBuilder getWaypointsPatchOrBuilder();

  /**
   * <code>optional .teamviewer.v1.TabPlayersReplace tab_players_replace = 16 [json_name = "tabPlayersReplace"];</code>
   * @return Whether the tabPlayersReplace field is set.
   */
  boolean hasTabPlayersReplace();
  /**
   * <code>optional .teamviewer.v1.TabPlayersReplace tab_players_replace = 16 [json_name = "tabPlayersReplace"];</code>
   * @return The tabPlayersReplace.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.TabPlayersReplace getTabPlayersReplace();
  /**
   * <code>optional .teamviewer.v1.TabPlayersReplace tab_players_replace = 16 [json_name = "tabPlayersReplace"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.TabPlayersReplaceOrBuilder getTabPlayersReplaceOrBuilder();

  /**
   * <code>optional .teamviewer.v1.TabPlayersPatchScope tab_players_patch = 17 [json_name = "tabPlayersPatch"];</code>
   * @return Whether the tabPlayersPatch field is set.
   */
  boolean hasTabPlayersPatch();
  /**
   * <code>optional .teamviewer.v1.TabPlayersPatchScope tab_players_patch = 17 [json_name = "tabPlayersPatch"];</code>
   * @return The tabPlayersPatch.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.TabPlayersPatchScope getTabPlayersPatch();
  /**
   * <code>optional .teamviewer.v1.TabPlayersPatchScope tab_players_patch = 17 [json_name = "tabPlayersPatch"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.TabPlayersPatchScopeOrBuilder getTabPlayersPatchOrBuilder();

  /**
   * <code>optional .teamviewer.v1.BattleMapObservation battle_map_observation = 18 [json_name = "battleMapObservation"];</code>
   * @return Whether the battleMapObservation field is set.
   */
  boolean hasBattleMapObservation();
  /**
   * <code>optional .teamviewer.v1.BattleMapObservation battle_map_observation = 18 [json_name = "battleMapObservation"];</code>
   * @return The battleMapObservation.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservation getBattleMapObservation();
  /**
   * <code>optional .teamviewer.v1.BattleMapObservation battle_map_observation = 18 [json_name = "battleMapObservation"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.BattleMapObservationOrBuilder getBattleMapObservationOrBuilder();

  /**
   * <code>optional .teamviewer.v1.StateKeepalive state_keepalive = 19 [json_name = "stateKeepalive"];</code>
   * @return Whether the stateKeepalive field is set.
   */
  boolean hasStateKeepalive();
  /**
   * <code>optional .teamviewer.v1.StateKeepalive state_keepalive = 19 [json_name = "stateKeepalive"];</code>
   * @return The stateKeepalive.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.StateKeepalive getStateKeepalive();
  /**
   * <code>optional .teamviewer.v1.StateKeepalive state_keepalive = 19 [json_name = "stateKeepalive"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.StateKeepaliveOrBuilder getStateKeepaliveOrBuilder();

  /**
   * <code>optional .teamviewer.v1.SourceStateClear source_state_clear = 20 [json_name = "sourceStateClear"];</code>
   * @return Whether the sourceStateClear field is set.
   */
  boolean hasSourceStateClear();
  /**
   * <code>optional .teamviewer.v1.SourceStateClear source_state_clear = 20 [json_name = "sourceStateClear"];</code>
   * @return The sourceStateClear.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.SourceStateClear getSourceStateClear();
  /**
   * <code>optional .teamviewer.v1.SourceStateClear source_state_clear = 20 [json_name = "sourceStateClear"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.SourceStateClearOrBuilder getSourceStateClearOrBuilder();

  /**
   * <code>optional .teamviewer.v1.WaypointsDelete waypoints_delete = 21 [json_name = "waypointsDelete"];</code>
   * @return Whether the waypointsDelete field is set.
   */
  boolean hasWaypointsDelete();
  /**
   * <code>optional .teamviewer.v1.WaypointsDelete waypoints_delete = 21 [json_name = "waypointsDelete"];</code>
   * @return The waypointsDelete.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDelete getWaypointsDelete();
  /**
   * <code>optional .teamviewer.v1.WaypointsDelete waypoints_delete = 21 [json_name = "waypointsDelete"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteOrBuilder getWaypointsDeleteOrBuilder();

  /**
   * <code>optional .teamviewer.v1.WaypointsEntityDeathCancel waypoints_entity_death_cancel = 22 [json_name = "waypointsEntityDeathCancel"];</code>
   * @return Whether the waypointsEntityDeathCancel field is set.
   */
  boolean hasWaypointsEntityDeathCancel();
  /**
   * <code>optional .teamviewer.v1.WaypointsEntityDeathCancel waypoints_entity_death_cancel = 22 [json_name = "waypointsEntityDeathCancel"];</code>
   * @return The waypointsEntityDeathCancel.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.WaypointsEntityDeathCancel getWaypointsEntityDeathCancel();
  /**
   * <code>optional .teamviewer.v1.WaypointsEntityDeathCancel waypoints_entity_death_cancel = 22 [json_name = "waypointsEntityDeathCancel"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.WaypointsEntityDeathCancelOrBuilder getWaypointsEntityDeathCancelOrBuilder();
}
