// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

/**
 * Protobuf type {@code teamviewer.v1.PlayersReplace}
 */
@com.google.protobuf.Generated
public final class PlayersReplace extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:teamviewer.v1.PlayersReplace)
    PlayersReplaceOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "PlayersReplace");
  }
  // Use PlayersReplace.newBuilder() to construct.
  private PlayersReplace(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PlayersReplace() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_PlayersReplace_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_PlayersReplace_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetPlayers();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_PlayersReplace_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace.class, fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace.Builder.class);
  }

  public static final int PLAYERS_FIELD_NUMBER = 1;
  private static final class PlayersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData>newDefaultInstance(
                fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_PlayersReplace_PlayersEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                fun.prof_chen.teamviewer.main_code.network.proto.PlayerData.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData> players_;
  private com.google.protobuf.MapField<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData>
  internalGetPlayers() {
    if (players_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PlayersDefaultEntryHolder.defaultEntry);
    }
    return players_;
  }
  public int getPlayersCount() {
    return internalGetPlayers().getMap().size();
  }
  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
   */
  @java.lang.Override
  public boolean containsPlayers(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetPlayers().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPlayersMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData> getPlayers() {
    return getPlayersMap();
  }
  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData> getPlayersMap() {
    return internalGetPlayers().getMap();
  }
  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
   */
  @java.lang.Override
  public /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.PlayerData getPlayersOrDefault(
      java.lang.String key,
      /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.PlayerData defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData> map =
        internalGetPlayers().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
   */
  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.PlayerData getPlayersOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData> map =
        internalGetPlayers().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetPlayers(),
        PlayersDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData> entry
         : internalGetPlayers().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData>
      players__ = PlayersDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .buildPartial();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, players__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace)) {
      return super.equals(obj);
    }
    fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace other = (fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace) obj;

    if (!internalGetPlayers().equals(
        other.internalGetPlayers())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetPlayers().getMap().isEmpty()) {
      hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetPlayers().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code teamviewer.v1.PlayersReplace}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:teamviewer.v1.PlayersReplace)
      fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplaceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_PlayersReplace_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetPlayers();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutablePlayers();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_PlayersReplace_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace.class, fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace.Builder.class);
    }

    // Construct using fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutablePlayers().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.internal_static_teamviewer_v1_PlayersReplace_descriptor;
    }

    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace getDefaultInstanceForType() {
      return fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace.getDefaultInstance();
    }

    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace build() {
      fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace buildPartial() {
      fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace result = new fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.players_ = internalGetPlayers().build(PlayersDefaultEntryHolder.defaultEntry);
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace) {
        return mergeFrom((fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace other) {
      if (other == fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace.getDefaultInstance()) return this;
      internalGetMutablePlayers().mergeFrom(
          other.internalGetPlayers());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData>
              players__ = input.readMessage(
                  PlayersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutablePlayers().ensureBuilderMap().put(
                  players__.getKey(), players__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private static final class PlayersConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerDataOrBuilder, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData> {
      @java.lang.Override
      public fun.prof_chen.teamviewer.main_code.network.proto.PlayerData build(fun.prof_chen.teamviewer.main_code.network.proto.PlayerDataOrBuilder val) {
        if (val instanceof fun.prof_chen.teamviewer.main_code.network.proto.PlayerData) { return (fun.prof_chen.teamviewer.main_code.network.proto.PlayerData) val; }
        return ((fun.prof_chen.teamviewer.main_code.network.proto.PlayerData.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData> defaultEntry() {
        return PlayersDefaultEntryHolder.defaultEntry;
      }
    };
    private static final PlayersConverter playersConverter = new PlayersConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerDataOrBuilder, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData.Builder> players_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerDataOrBuilder, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData.Builder>
        internalGetPlayers() {
      if (players_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(playersConverter);
      }
      return players_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerDataOrBuilder, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData.Builder>
        internalGetMutablePlayers() {
      if (players_ == null) {
        players_ = new com.google.protobuf.MapFieldBuilder<>(playersConverter);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return players_;
    }
    public int getPlayersCount() {
      return internalGetPlayers().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
     */
    @java.lang.Override
    public boolean containsPlayers(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetPlayers().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getPlayersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData> getPlayers() {
      return getPlayersMap();
    }
    /**
     * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData> getPlayersMap() {
      return internalGetPlayers().getImmutableMap();
    }
    /**
     * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
     */
    @java.lang.Override
    public /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.PlayerData getPlayersOrDefault(
        java.lang.String key,
        /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.PlayerData defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerDataOrBuilder> map = internalGetMutablePlayers().ensureBuilderMap();
      return map.containsKey(key) ? playersConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
     */
    @java.lang.Override
    public fun.prof_chen.teamviewer.main_code.network.proto.PlayerData getPlayersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerDataOrBuilder> map = internalGetMutablePlayers().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return playersConverter.build(map.get(key));
    }
    public Builder clearPlayers() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutablePlayers().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
     */
    public Builder removePlayers(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutablePlayers().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData>
        getMutablePlayers() {
      bitField0_ |= 0x00000001;
      return internalGetMutablePlayers().ensureMessageMap();
    }
    /**
     * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
     */
    public Builder putPlayers(
        java.lang.String key,
        fun.prof_chen.teamviewer.main_code.network.proto.PlayerData value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutablePlayers().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
     */
    public Builder putAllPlayers(
        java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData> values) {
      for (java.util.Map.Entry<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutablePlayers().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
     */
    public fun.prof_chen.teamviewer.main_code.network.proto.PlayerData.Builder putPlayersBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerDataOrBuilder> builderMap = internalGetMutablePlayers().ensureBuilderMap();
      fun.prof_chen.teamviewer.main_code.network.proto.PlayerDataOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = fun.prof_chen.teamviewer.main_code.network.proto.PlayerData.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof fun.prof_chen.teamviewer.main_code.network.proto.PlayerData) {
        entry = ((fun.prof_chen.teamviewer.main_code.network.proto.PlayerData) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (fun.prof_chen.teamviewer.main_code.network.proto.PlayerData.Builder) entry;
    }

    // @@protoc_insertion_point(builder_scope:teamviewer.v1.PlayersReplace)
  }

  // @@protoc_insertion_point(class_scope:teamviewer.v1.PlayersReplace)
  private static final fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace();
  }

  public static fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlayersReplace>
      PARSER = new com.google.protobuf.AbstractParser<PlayersReplace>() {
    @java.lang.Override
    public PlayersReplace parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PlayersReplace> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlayersReplace> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fun.prof_chen.teamviewer.main_code.network.proto.PlayersReplace getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

