// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

@com.google.protobuf.Generated
public interface RefreshRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teamviewer.v1.RefreshRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reason = 1 [json_name = "reason"];</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 1 [json_name = "reason"];</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>double server_time = 2 [json_name = "serverTime"];</code>
   * @return The serverTime.
   */
  double getServerTime();

  /**
   * <code>repeated string players = 3 [json_name = "players"];</code>
   * @return A list containing the players.
   */
  java.util.List<java.lang.String>
      getPlayersList();
  /**
   * <code>repeated string players = 3 [json_name = "players"];</code>
   * @return The count of players.
   */
  int getPlayersCount();
  /**
   * <code>repeated string players = 3 [json_name = "players"];</code>
   * @param index The index of the element to return.
   * @return The players at the given index.
   */
  java.lang.String getPlayers(int index);
  /**
   * <code>repeated string players = 3 [json_name = "players"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the players at the given index.
   */
  com.google.protobuf.ByteString
      getPlayersBytes(int index);

  /**
   * <code>repeated string entities = 4 [json_name = "entities"];</code>
   * @return A list containing the entities.
   */
  java.util.List<java.lang.String>
      getEntitiesList();
  /**
   * <code>repeated string entities = 4 [json_name = "entities"];</code>
   * @return The count of entities.
   */
  int getEntitiesCount();
  /**
   * <code>repeated string entities = 4 [json_name = "entities"];</code>
   * @param index The index of the element to return.
   * @return The entities at the given index.
   */
  java.lang.String getEntities(int index);
  /**
   * <code>repeated string entities = 4 [json_name = "entities"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the entities at the given index.
   */
  com.google.protobuf.ByteString
      getEntitiesBytes(int index);

  /**
   * <code>repeated string battle_chunks = 5 [json_name = "battleChunks"];</code>
   * @return A list containing the battleChunks.
   */
  java.util.List<java.lang.String>
      getBattleChunksList();
  /**
   * <code>repeated string battle_chunks = 5 [json_name = "battleChunks"];</code>
   * @return The count of battleChunks.
   */
  int getBattleChunksCount();
  /**
   * <code>repeated string battle_chunks = 5 [json_name = "battleChunks"];</code>
   * @param index The index of the element to return.
   * @return The battleChunks at the given index.
   */
  java.lang.String getBattleChunks(int index);
  /**
   * <code>repeated string battle_chunks = 5 [json_name = "battleChunks"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the battleChunks at the given index.
   */
  com.google.protobuf.ByteString
      getBattleChunksBytes(int index);
}
