// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.29.3

package fun.prof_chen.teamviewer.main_code.network.proto;

public interface ReportRateHintOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teamviewer.v1.ReportRateHint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 report_interval_ticks = 1;</code>
   * @return The reportIntervalTicks.
   */
  int getReportIntervalTicks();

  /**
   * <code>double broadcast_hz = 2;</code>
   * @return The broadcastHz.
   */
  double getBroadcastHz();

  /**
   * <code>optional string reason = 3;</code>
   * @return Whether the reason field is set.
   */
  boolean hasReason();
  /**
   * <code>optional string reason = 3;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>optional string reason = 3;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
