// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

@com.google.protobuf.Generated
public interface ResyncRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teamviewer.v1.ResyncRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string reason = 1 [json_name = "reason"];</code>
   * @return Whether the reason field is set.
   */
  boolean hasReason();
  /**
   * <code>optional string reason = 1 [json_name = "reason"];</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>optional string reason = 1 [json_name = "reason"];</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
