// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.29.3

package fun.prof_chen.teamviewer.main_code.network.proto;

public interface SameServerGroupListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teamviewer.v1.SameServerGroupList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .teamviewer.v1.SameServerGroup values = 1;</code>
   */
  java.util.List<fun.prof_chen.teamviewer.main_code.network.proto.SameServerGroup> 
      getValuesList();
  /**
   * <code>repeated .teamviewer.v1.SameServerGroup values = 1;</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.SameServerGroup getValues(int index);
  /**
   * <code>repeated .teamviewer.v1.SameServerGroup values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .teamviewer.v1.SameServerGroup values = 1;</code>
   */
  java.util.List<? extends fun.prof_chen.teamviewer.main_code.network.proto.SameServerGroupOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .teamviewer.v1.SameServerGroup values = 1;</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.SameServerGroupOrBuilder getValuesOrBuilder(
      int index);
}
