// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

@com.google.protobuf.Generated
public interface SnapshotFullOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teamviewer.v1.SnapshotFull)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
   */
  int getPlayersCount();
  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
   */
  boolean containsPlayers(
      java.lang.String key);
  /**
   * Use {@link #getPlayersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData>
  getPlayers();
  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
   */
  java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerData>
  getPlayersMap();
  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
   */
  /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.PlayerData getPlayersOrDefault(
      java.lang.String key,
      /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.PlayerData defaultValue);
  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerData&gt; players = 1 [json_name = "players"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.PlayerData getPlayersOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, .teamviewer.v1.EntityData&gt; entities = 2 [json_name = "entities"];</code>
   */
  int getEntitiesCount();
  /**
   * <code>map&lt;string, .teamviewer.v1.EntityData&gt; entities = 2 [json_name = "entities"];</code>
   */
  boolean containsEntities(
      java.lang.String key);
  /**
   * Use {@link #getEntitiesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.EntityData>
  getEntities();
  /**
   * <code>map&lt;string, .teamviewer.v1.EntityData&gt; entities = 2 [json_name = "entities"];</code>
   */
  java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.EntityData>
  getEntitiesMap();
  /**
   * <code>map&lt;string, .teamviewer.v1.EntityData&gt; entities = 2 [json_name = "entities"];</code>
   */
  /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.EntityData getEntitiesOrDefault(
      java.lang.String key,
      /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.EntityData defaultValue);
  /**
   * <code>map&lt;string, .teamviewer.v1.EntityData&gt; entities = 2 [json_name = "entities"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.EntityData getEntitiesOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, .teamviewer.v1.WaypointData&gt; waypoints = 3 [json_name = "waypoints"];</code>
   */
  int getWaypointsCount();
  /**
   * <code>map&lt;string, .teamviewer.v1.WaypointData&gt; waypoints = 3 [json_name = "waypoints"];</code>
   */
  boolean containsWaypoints(
      java.lang.String key);
  /**
   * Use {@link #getWaypointsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.WaypointData>
  getWaypoints();
  /**
   * <code>map&lt;string, .teamviewer.v1.WaypointData&gt; waypoints = 3 [json_name = "waypoints"];</code>
   */
  java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.WaypointData>
  getWaypointsMap();
  /**
   * <code>map&lt;string, .teamviewer.v1.WaypointData&gt; waypoints = 3 [json_name = "waypoints"];</code>
   */
  /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.WaypointData getWaypointsOrDefault(
      java.lang.String key,
      /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.WaypointData defaultValue);
  /**
   * <code>map&lt;string, .teamviewer.v1.WaypointData&gt; waypoints = 3 [json_name = "waypoints"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.WaypointData getWaypointsOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, .teamviewer.v1.BattleChunkData&gt; battle_chunks = 4 [json_name = "battleChunks"];</code>
   */
  int getBattleChunksCount();
  /**
   * <code>map&lt;string, .teamviewer.v1.BattleChunkData&gt; battle_chunks = 4 [json_name = "battleChunks"];</code>
   */
  boolean containsBattleChunks(
      java.lang.String key);
  /**
   * Use {@link #getBattleChunksMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.BattleChunkData>
  getBattleChunks();
  /**
   * <code>map&lt;string, .teamviewer.v1.BattleChunkData&gt; battle_chunks = 4 [json_name = "battleChunks"];</code>
   */
  java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.BattleChunkData>
  getBattleChunksMap();
  /**
   * <code>map&lt;string, .teamviewer.v1.BattleChunkData&gt; battle_chunks = 4 [json_name = "battleChunks"];</code>
   */
  /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.BattleChunkData getBattleChunksOrDefault(
      java.lang.String key,
      /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.BattleChunkData defaultValue);
  /**
   * <code>map&lt;string, .teamviewer.v1.BattleChunkData&gt; battle_chunks = 4 [json_name = "battleChunks"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.BattleChunkData getBattleChunksOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerMark&gt; player_marks = 5 [json_name = "playerMarks"];</code>
   */
  int getPlayerMarksCount();
  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerMark&gt; player_marks = 5 [json_name = "playerMarks"];</code>
   */
  boolean containsPlayerMarks(
      java.lang.String key);
  /**
   * Use {@link #getPlayerMarksMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerMark>
  getPlayerMarks();
  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerMark&gt; player_marks = 5 [json_name = "playerMarks"];</code>
   */
  java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.PlayerMark>
  getPlayerMarksMap();
  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerMark&gt; player_marks = 5 [json_name = "playerMarks"];</code>
   */
  /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.PlayerMark getPlayerMarksOrDefault(
      java.lang.String key,
      /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.PlayerMark defaultValue);
  /**
   * <code>map&lt;string, .teamviewer.v1.PlayerMark&gt; player_marks = 5 [json_name = "playerMarks"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.PlayerMark getPlayerMarksOrThrow(
      java.lang.String key);

  /**
   * <code>optional .teamviewer.v1.WebMapTabState tab_state = 6 [json_name = "tabState"];</code>
   * @return Whether the tabState field is set.
   */
  boolean hasTabState();
  /**
   * <code>optional .teamviewer.v1.WebMapTabState tab_state = 6 [json_name = "tabState"];</code>
   * @return The tabState.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.WebMapTabState getTabState();
  /**
   * <code>optional .teamviewer.v1.WebMapTabState tab_state = 6 [json_name = "tabState"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.WebMapTabStateOrBuilder getTabStateOrBuilder();

  /**
   * <code>optional string room_code = 7 [json_name = "roomCode"];</code>
   * @return Whether the roomCode field is set.
   */
  boolean hasRoomCode();
  /**
   * <code>optional string room_code = 7 [json_name = "roomCode"];</code>
   * @return The roomCode.
   */
  java.lang.String getRoomCode();
  /**
   * <code>optional string room_code = 7 [json_name = "roomCode"];</code>
   * @return The bytes for roomCode.
   */
  com.google.protobuf.ByteString
      getRoomCodeBytes();

  /**
   * <code>repeated string connections = 8 [json_name = "connections"];</code>
   * @return A list containing the connections.
   */
  java.util.List<java.lang.String>
      getConnections8List();
  /**
   * <code>repeated string connections = 8 [json_name = "connections"];</code>
   * @return The count of connections.
   */
  int getConnections8Count();
  /**
   * <code>repeated string connections = 8 [json_name = "connections"];</code>
   * @param index The index of the element to return.
   * @return The connections at the given index.
   */
  java.lang.String getConnections8(int index);
  /**
   * <code>repeated string connections = 8 [json_name = "connections"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the connections at the given index.
   */
  com.google.protobuf.ByteString
      getConnections8Bytes(int index);

  /**
   * <code>optional int32 connections_count = 9 [json_name = "connectionsCount"];</code>
   * @return Whether the connectionsCount field is set.
   */
  boolean hasConnectionsCount9();
  /**
   * <code>optional int32 connections_count = 9 [json_name = "connectionsCount"];</code>
   * @return The connectionsCount.
   */
  int getConnectionsCount9();

  /**
   * <code>optional double server_time = 10 [json_name = "serverTime"];</code>
   * @return Whether the serverTime field is set.
   */
  boolean hasServerTime();
  /**
   * <code>optional double server_time = 10 [json_name = "serverTime"];</code>
   * @return The serverTime.
   */
  double getServerTime();
}
