// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

@com.google.protobuf.Generated
public interface TabStatePatchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teamviewer.v1.TabStatePatch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool enabled = 1 [json_name = "enabled"];</code>
   * @return Whether the enabled field is set.
   */
  boolean hasEnabled();
  /**
   * <code>optional bool enabled = 1 [json_name = "enabled"];</code>
   * @return The enabled.
   */
  boolean getEnabled();

  /**
   * <code>optional string room_code = 2 [json_name = "roomCode"];</code>
   * @return Whether the roomCode field is set.
   */
  boolean hasRoomCode();
  /**
   * <code>optional string room_code = 2 [json_name = "roomCode"];</code>
   * @return The roomCode.
   */
  java.lang.String getRoomCode();
  /**
   * <code>optional string room_code = 2 [json_name = "roomCode"];</code>
   * @return The bytes for roomCode.
   */
  com.google.protobuf.ByteString
      getRoomCodeBytes();

  /**
   * <code>optional .teamviewer.v1.SameServerGroupList groups = 3 [json_name = "groups"];</code>
   * @return Whether the groups field is set.
   */
  boolean hasGroups();
  /**
   * <code>optional .teamviewer.v1.SameServerGroupList groups = 3 [json_name = "groups"];</code>
   * @return The groups.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.SameServerGroupList getGroups();
  /**
   * <code>optional .teamviewer.v1.SameServerGroupList groups = 3 [json_name = "groups"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.SameServerGroupListOrBuilder getGroupsOrBuilder();

  /**
   * <code>map&lt;string, .teamviewer.v1.TabPlayerReport&gt; upsert_reports = 4 [json_name = "upsertReports"];</code>
   */
  int getUpsertReportsCount();
  /**
   * <code>map&lt;string, .teamviewer.v1.TabPlayerReport&gt; upsert_reports = 4 [json_name = "upsertReports"];</code>
   */
  boolean containsUpsertReports(
      java.lang.String key);
  /**
   * Use {@link #getUpsertReportsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.TabPlayerReport>
  getUpsertReports();
  /**
   * <code>map&lt;string, .teamviewer.v1.TabPlayerReport&gt; upsert_reports = 4 [json_name = "upsertReports"];</code>
   */
  java.util.Map<java.lang.String, fun.prof_chen.teamviewer.main_code.network.proto.TabPlayerReport>
  getUpsertReportsMap();
  /**
   * <code>map&lt;string, .teamviewer.v1.TabPlayerReport&gt; upsert_reports = 4 [json_name = "upsertReports"];</code>
   */
  /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.TabPlayerReport getUpsertReportsOrDefault(
      java.lang.String key,
      /* nullable */
fun.prof_chen.teamviewer.main_code.network.proto.TabPlayerReport defaultValue);
  /**
   * <code>map&lt;string, .teamviewer.v1.TabPlayerReport&gt; upsert_reports = 4 [json_name = "upsertReports"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.TabPlayerReport getUpsertReportsOrThrow(
      java.lang.String key);

  /**
   * <code>repeated string delete_reports = 5 [json_name = "deleteReports"];</code>
   * @return A list containing the deleteReports.
   */
  java.util.List<java.lang.String>
      getDeleteReportsList();
  /**
   * <code>repeated string delete_reports = 5 [json_name = "deleteReports"];</code>
   * @return The count of deleteReports.
   */
  int getDeleteReportsCount();
  /**
   * <code>repeated string delete_reports = 5 [json_name = "deleteReports"];</code>
   * @param index The index of the element to return.
   * @return The deleteReports at the given index.
   */
  java.lang.String getDeleteReports(int index);
  /**
   * <code>repeated string delete_reports = 5 [json_name = "deleteReports"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the deleteReports at the given index.
   */
  com.google.protobuf.ByteString
      getDeleteReportsBytes(int index);
}
