// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

@com.google.protobuf.Generated
public interface WaypointsEntityDeathCancelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teamviewer.v1.WaypointsEntityDeathCancel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string target_entity_ids = 1 [json_name = "targetEntityIds"];</code>
   * @return A list containing the targetEntityIds.
   */
  java.util.List<java.lang.String>
      getTargetEntityIdsList();
  /**
   * <code>repeated string target_entity_ids = 1 [json_name = "targetEntityIds"];</code>
   * @return The count of targetEntityIds.
   */
  int getTargetEntityIdsCount();
  /**
   * <code>repeated string target_entity_ids = 1 [json_name = "targetEntityIds"];</code>
   * @param index The index of the element to return.
   * @return The targetEntityIds at the given index.
   */
  java.lang.String getTargetEntityIds(int index);
  /**
   * <code>repeated string target_entity_ids = 1 [json_name = "targetEntityIds"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the targetEntityIds at the given index.
   */
  com.google.protobuf.ByteString
      getTargetEntityIdsBytes(int index);
}
