// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

@com.google.protobuf.Generated
public interface WaypointDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teamviewer.v1.WaypointData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double x = 1 [json_name = "x"];</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 2 [json_name = "y"];</code>
   * @return The y.
   */
  double getY();

  /**
   * <code>double z = 3 [json_name = "z"];</code>
   * @return The z.
   */
  double getZ();

  /**
   * <code>string dimension = 4 [json_name = "dimension"];</code>
   * @return The dimension.
   */
  java.lang.String getDimension();
  /**
   * <code>string dimension = 4 [json_name = "dimension"];</code>
   * @return The bytes for dimension.
   */
  com.google.protobuf.ByteString
      getDimensionBytes();

  /**
   * <code>string name = 5 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 5 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string symbol = 6 [json_name = "symbol"];</code>
   * @return Whether the symbol field is set.
   */
  boolean hasSymbol();
  /**
   * <code>optional string symbol = 6 [json_name = "symbol"];</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>optional string symbol = 6 [json_name = "symbol"];</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>optional int32 color = 7 [json_name = "color"];</code>
   * @return Whether the color field is set.
   */
  boolean hasColor();
  /**
   * <code>optional int32 color = 7 [json_name = "color"];</code>
   * @return The color.
   */
  int getColor();

  /**
   * <code>optional string owner_id = 8 [json_name = "ownerId"];</code>
   * @return Whether the ownerId field is set.
   */
  boolean hasOwnerId();
  /**
   * <code>optional string owner_id = 8 [json_name = "ownerId"];</code>
   * @return The ownerId.
   */
  java.lang.String getOwnerId();
  /**
   * <code>optional string owner_id = 8 [json_name = "ownerId"];</code>
   * @return The bytes for ownerId.
   */
  com.google.protobuf.ByteString
      getOwnerIdBytes();

  /**
   * <code>optional string owner_name = 9 [json_name = "ownerName"];</code>
   * @return Whether the ownerName field is set.
   */
  boolean hasOwnerName();
  /**
   * <code>optional string owner_name = 9 [json_name = "ownerName"];</code>
   * @return The ownerName.
   */
  java.lang.String getOwnerName();
  /**
   * <code>optional string owner_name = 9 [json_name = "ownerName"];</code>
   * @return The bytes for ownerName.
   */
  com.google.protobuf.ByteString
      getOwnerNameBytes();

  /**
   * <code>optional int64 created_at = 10 [json_name = "createdAt"];</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>optional int64 created_at = 10 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  long getCreatedAt();

  /**
   * <code>optional int32 ttl_seconds = 11 [json_name = "ttlSeconds"];</code>
   * @return Whether the ttlSeconds field is set.
   */
  boolean hasTtlSeconds();
  /**
   * <code>optional int32 ttl_seconds = 11 [json_name = "ttlSeconds"];</code>
   * @return The ttlSeconds.
   */
  int getTtlSeconds();

  /**
   * <code>optional string waypoint_kind = 12 [json_name = "waypointKind"];</code>
   * @return Whether the waypointKind field is set.
   */
  boolean hasWaypointKind();
  /**
   * <code>optional string waypoint_kind = 12 [json_name = "waypointKind"];</code>
   * @return The waypointKind.
   */
  java.lang.String getWaypointKind();
  /**
   * <code>optional string waypoint_kind = 12 [json_name = "waypointKind"];</code>
   * @return The bytes for waypointKind.
   */
  com.google.protobuf.ByteString
      getWaypointKindBytes();

  /**
   * <code>optional bool replace_old_quick = 13 [json_name = "replaceOldQuick"];</code>
   * @return Whether the replaceOldQuick field is set.
   */
  boolean hasReplaceOldQuick();
  /**
   * <code>optional bool replace_old_quick = 13 [json_name = "replaceOldQuick"];</code>
   * @return The replaceOldQuick.
   */
  boolean getReplaceOldQuick();

  /**
   * <code>optional int32 max_quick_marks = 14 [json_name = "maxQuickMarks"];</code>
   * @return Whether the maxQuickMarks field is set.
   */
  boolean hasMaxQuickMarks();
  /**
   * <code>optional int32 max_quick_marks = 14 [json_name = "maxQuickMarks"];</code>
   * @return The maxQuickMarks.
   */
  int getMaxQuickMarks();

  /**
   * <code>optional string target_type = 15 [json_name = "targetType"];</code>
   * @return Whether the targetType field is set.
   */
  boolean hasTargetType();
  /**
   * <code>optional string target_type = 15 [json_name = "targetType"];</code>
   * @return The targetType.
   */
  java.lang.String getTargetType();
  /**
   * <code>optional string target_type = 15 [json_name = "targetType"];</code>
   * @return The bytes for targetType.
   */
  com.google.protobuf.ByteString
      getTargetTypeBytes();

  /**
   * <code>optional string target_entity_id = 16 [json_name = "targetEntityId"];</code>
   * @return Whether the targetEntityId field is set.
   */
  boolean hasTargetEntityId();
  /**
   * <code>optional string target_entity_id = 16 [json_name = "targetEntityId"];</code>
   * @return The targetEntityId.
   */
  java.lang.String getTargetEntityId();
  /**
   * <code>optional string target_entity_id = 16 [json_name = "targetEntityId"];</code>
   * @return The bytes for targetEntityId.
   */
  com.google.protobuf.ByteString
      getTargetEntityIdBytes();

  /**
   * <code>optional string target_entity_type = 17 [json_name = "targetEntityType"];</code>
   * @return Whether the targetEntityType field is set.
   */
  boolean hasTargetEntityType();
  /**
   * <code>optional string target_entity_type = 17 [json_name = "targetEntityType"];</code>
   * @return The targetEntityType.
   */
  java.lang.String getTargetEntityType();
  /**
   * <code>optional string target_entity_type = 17 [json_name = "targetEntityType"];</code>
   * @return The bytes for targetEntityType.
   */
  com.google.protobuf.ByteString
      getTargetEntityTypeBytes();

  /**
   * <code>optional string target_entity_name = 18 [json_name = "targetEntityName"];</code>
   * @return Whether the targetEntityName field is set.
   */
  boolean hasTargetEntityName();
  /**
   * <code>optional string target_entity_name = 18 [json_name = "targetEntityName"];</code>
   * @return The targetEntityName.
   */
  java.lang.String getTargetEntityName();
  /**
   * <code>optional string target_entity_name = 18 [json_name = "targetEntityName"];</code>
   * @return The bytes for targetEntityName.
   */
  com.google.protobuf.ByteString
      getTargetEntityNameBytes();

  /**
   * <code>optional string room_code = 19 [json_name = "roomCode"];</code>
   * @return Whether the roomCode field is set.
   */
  boolean hasRoomCode();
  /**
   * <code>optional string room_code = 19 [json_name = "roomCode"];</code>
   * @return The roomCode.
   */
  java.lang.String getRoomCode();
  /**
   * <code>optional string room_code = 19 [json_name = "roomCode"];</code>
   * @return The bytes for roomCode.
   */
  com.google.protobuf.ByteString
      getRoomCodeBytes();

  /**
   * <code>optional bool permanent = 20 [json_name = "permanent"];</code>
   * @return Whether the permanent field is set.
   */
  boolean hasPermanent();
  /**
   * <code>optional bool permanent = 20 [json_name = "permanent"];</code>
   * @return The permanent.
   */
  boolean getPermanent();

  /**
   * <code>optional string tactical_type = 21 [json_name = "tacticalType"];</code>
   * @return Whether the tacticalType field is set.
   */
  boolean hasTacticalType();
  /**
   * <code>optional string tactical_type = 21 [json_name = "tacticalType"];</code>
   * @return The tacticalType.
   */
  java.lang.String getTacticalType();
  /**
   * <code>optional string tactical_type = 21 [json_name = "tacticalType"];</code>
   * @return The bytes for tacticalType.
   */
  com.google.protobuf.ByteString
      getTacticalTypeBytes();

  /**
   * <code>optional string source_type = 22 [json_name = "sourceType"];</code>
   * @return Whether the sourceType field is set.
   */
  boolean hasSourceType();
  /**
   * <code>optional string source_type = 22 [json_name = "sourceType"];</code>
   * @return The sourceType.
   */
  java.lang.String getSourceType();
  /**
   * <code>optional string source_type = 22 [json_name = "sourceType"];</code>
   * @return The bytes for sourceType.
   */
  com.google.protobuf.ByteString
      getSourceTypeBytes();

  /**
   * <code>optional string deletable_by = 23 [json_name = "deletableBy"];</code>
   * @return Whether the deletableBy field is set.
   */
  boolean hasDeletableBy();
  /**
   * <code>optional string deletable_by = 23 [json_name = "deletableBy"];</code>
   * @return The deletableBy.
   */
  java.lang.String getDeletableBy();
  /**
   * <code>optional string deletable_by = 23 [json_name = "deletableBy"];</code>
   * @return The bytes for deletableBy.
   */
  com.google.protobuf.ByteString
      getDeletableByBytes();
}
