// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

@com.google.protobuf.Generated
public interface WebMapClearAllPlayerMarksAckDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teamviewer.v1.WebMapClearAllPlayerMarksAckDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 removed_count = 1 [json_name = "removedCount"];</code>
   * @return The removedCount.
   */
  int getRemovedCount();
}
