// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

@com.google.protobuf.Generated
public interface WebMapCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teamviewer.v1.WebMapCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.teamviewer.v1.ResyncRequest resync_request = 1 [json_name = "resyncRequest"];</code>
   * @return Whether the resyncRequest field is set.
   */
  boolean hasResyncRequest();
  /**
   * <code>.teamviewer.v1.ResyncRequest resync_request = 1 [json_name = "resyncRequest"];</code>
   * @return The resyncRequest.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.ResyncRequest getResyncRequest();
  /**
   * <code>.teamviewer.v1.ResyncRequest resync_request = 1 [json_name = "resyncRequest"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.ResyncRequestOrBuilder getResyncRequestOrBuilder();

  /**
   * <code>.teamviewer.v1.CommandPlayerMarkSet set_player_mark = 2 [json_name = "setPlayerMark"];</code>
   * @return Whether the setPlayerMark field is set.
   */
  boolean hasSetPlayerMark();
  /**
   * <code>.teamviewer.v1.CommandPlayerMarkSet set_player_mark = 2 [json_name = "setPlayerMark"];</code>
   * @return The setPlayerMark.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.CommandPlayerMarkSet getSetPlayerMark();
  /**
   * <code>.teamviewer.v1.CommandPlayerMarkSet set_player_mark = 2 [json_name = "setPlayerMark"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.CommandPlayerMarkSetOrBuilder getSetPlayerMarkOrBuilder();

  /**
   * <code>.teamviewer.v1.CommandPlayerMarkClear clear_player_mark = 3 [json_name = "clearPlayerMark"];</code>
   * @return Whether the clearPlayerMark field is set.
   */
  boolean hasClearPlayerMark();
  /**
   * <code>.teamviewer.v1.CommandPlayerMarkClear clear_player_mark = 3 [json_name = "clearPlayerMark"];</code>
   * @return The clearPlayerMark.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.CommandPlayerMarkClear getClearPlayerMark();
  /**
   * <code>.teamviewer.v1.CommandPlayerMarkClear clear_player_mark = 3 [json_name = "clearPlayerMark"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.CommandPlayerMarkClearOrBuilder getClearPlayerMarkOrBuilder();

  /**
   * <code>.teamviewer.v1.CommandPlayerMarkClearAll clear_all_player_marks = 4 [json_name = "clearAllPlayerMarks"];</code>
   * @return Whether the clearAllPlayerMarks field is set.
   */
  boolean hasClearAllPlayerMarks();
  /**
   * <code>.teamviewer.v1.CommandPlayerMarkClearAll clear_all_player_marks = 4 [json_name = "clearAllPlayerMarks"];</code>
   * @return The clearAllPlayerMarks.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.CommandPlayerMarkClearAll getClearAllPlayerMarks();
  /**
   * <code>.teamviewer.v1.CommandPlayerMarkClearAll clear_all_player_marks = 4 [json_name = "clearAllPlayerMarks"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.CommandPlayerMarkClearAllOrBuilder getClearAllPlayerMarksOrBuilder();

  /**
   * <code>.teamviewer.v1.CommandSameServerFilterSet set_same_server_filter = 5 [json_name = "setSameServerFilter"];</code>
   * @return Whether the setSameServerFilter field is set.
   */
  boolean hasSetSameServerFilter();
  /**
   * <code>.teamviewer.v1.CommandSameServerFilterSet set_same_server_filter = 5 [json_name = "setSameServerFilter"];</code>
   * @return The setSameServerFilter.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.CommandSameServerFilterSet getSetSameServerFilter();
  /**
   * <code>.teamviewer.v1.CommandSameServerFilterSet set_same_server_filter = 5 [json_name = "setSameServerFilter"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.CommandSameServerFilterSetOrBuilder getSetSameServerFilterOrBuilder();

  /**
   * <code>.teamviewer.v1.CommandTacticalWaypointSet set_tactical_waypoint = 6 [json_name = "setTacticalWaypoint"];</code>
   * @return Whether the setTacticalWaypoint field is set.
   */
  boolean hasSetTacticalWaypoint();
  /**
   * <code>.teamviewer.v1.CommandTacticalWaypointSet set_tactical_waypoint = 6 [json_name = "setTacticalWaypoint"];</code>
   * @return The setTacticalWaypoint.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSet getSetTacticalWaypoint();
  /**
   * <code>.teamviewer.v1.CommandTacticalWaypointSet set_tactical_waypoint = 6 [json_name = "setTacticalWaypoint"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.CommandTacticalWaypointSetOrBuilder getSetTacticalWaypointOrBuilder();

  /**
   * <code>.teamviewer.v1.WaypointsDelete delete_waypoints = 7 [json_name = "deleteWaypoints"];</code>
   * @return Whether the deleteWaypoints field is set.
   */
  boolean hasDeleteWaypoints();
  /**
   * <code>.teamviewer.v1.WaypointsDelete delete_waypoints = 7 [json_name = "deleteWaypoints"];</code>
   * @return The deleteWaypoints.
   */
  fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDelete getDeleteWaypoints();
  /**
   * <code>.teamviewer.v1.WaypointsDelete delete_waypoints = 7 [json_name = "deleteWaypoints"];</code>
   */
  fun.prof_chen.teamviewer.main_code.network.proto.WaypointsDeleteOrBuilder getDeleteWaypointsOrBuilder();

  fun.prof_chen.teamviewer.main_code.network.proto.WebMapCommand.CommandCase getCommandCase();
}
