// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: teamviewer/v1/teamviewer.proto
// Protobuf Java Version: 4.34.1

package fun.prof_chen.teamviewer.main_code.network.proto;

/**
 * Protobuf enum {@code teamviewer.v1.WireChannel}
 */
@com.google.protobuf.Generated
public enum WireChannel
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>WIRE_CHANNEL_UNSPECIFIED = 0;</code>
   */
  WIRE_CHANNEL_UNSPECIFIED(0),
  /**
   * <code>WIRE_CHANNEL_PLAYER = 1;</code>
   */
  WIRE_CHANNEL_PLAYER(1),
  /**
   * <code>WIRE_CHANNEL_WEB_MAP = 2;</code>
   */
  WIRE_CHANNEL_WEB_MAP(2),
  /**
   * <code>WIRE_CHANNEL_ADMIN = 3;</code>
   */
  WIRE_CHANNEL_ADMIN(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "WireChannel");
  }
  /**
   * <code>WIRE_CHANNEL_UNSPECIFIED = 0;</code>
   */
  public static final int WIRE_CHANNEL_UNSPECIFIED_VALUE = 0;
  /**
   * <code>WIRE_CHANNEL_PLAYER = 1;</code>
   */
  public static final int WIRE_CHANNEL_PLAYER_VALUE = 1;
  /**
   * <code>WIRE_CHANNEL_WEB_MAP = 2;</code>
   */
  public static final int WIRE_CHANNEL_WEB_MAP_VALUE = 2;
  /**
   * <code>WIRE_CHANNEL_ADMIN = 3;</code>
   */
  public static final int WIRE_CHANNEL_ADMIN_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static WireChannel valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static WireChannel forNumber(int value) {
    switch (value) {
      case 0: return WIRE_CHANNEL_UNSPECIFIED;
      case 1: return WIRE_CHANNEL_PLAYER;
      case 2: return WIRE_CHANNEL_WEB_MAP;
      case 3: return WIRE_CHANNEL_ADMIN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<WireChannel>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      WireChannel> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<WireChannel>() {
          public WireChannel findValueByNumber(int number) {
            return WireChannel.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return fun.prof_chen.teamviewer.main_code.network.proto.TeamviewerProto.getDescriptor().getEnumType(0);
  }

  private static final WireChannel[] VALUES = values();

  public static WireChannel valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private WireChannel(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:teamviewer.v1.WireChannel)
}

