plugins {
    id 'java-library'
}

dependencies {
    implementation "org.ow2.asm:asm:${project.asm_version}"
    implementation "org.ow2.asm:asm-commons:${project.asm_version}"
    testImplementation platform("org.junit:junit-bom:5.13.4")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

tasks.named("test") {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release.set(rootProject.ext.sharedJavaRelease as int)
}

java {
    def javaVersion = JavaVersion.toVersion(rootProject.ext.sharedJavaRelease as int)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(rootProject.ext.sharedJavaRelease as int)
    }
}
