modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/MC-TeamViewer/Minecraft_TeamViewer/issues"

[[mods]]
modId="team_view_relay"
version="${mod_version}"
displayName="TeamViewRelay"
description='''
用于团队协同作战的视野与报点共享系统。支持同步玩家位置、实体信息与共享路标。
'''
authors="Prof. Chen"
displayURL="https://github.com/MC-TeamViewer/Minecraft_TeamViewer"
logoFile="assets/teamviewer/icon.ico"
displayTest="IGNORE_ALL_VERSION"

[[dependencies.team_view_relay]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.team_view_relay]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="teamviewer.neoforge.client.mixins.json"

[features.team_view_relay]
javaVersion="[${java_version},)"
