package fun.prof_chen.teamviewer.main_code.config.ui;

public enum ConfigPageId {
    ROOT,
    DISPLAY,
    NETWORK,
    ENTITY_UPLOAD,
    ENTITY_FILTERS,
    ENTITY_FILTER_EDIT,
    COLOR,
    WAYPOINT,
    WAYPOINT_SHAPE,
    PACKET_CAPTURE,
    PLUGINS,
    PLUGIN_DETAIL,
    PLUGIN_RUNTIME_ACTION_CONFIRM,
    PLUGIN_COPY_GUIDE,
    DISABLED_PLUGINS,
    DISABLED_PLUGIN_DETAIL,
    PLUGIN_DELETE_CONFIRM
}
