pluginManagement {
    def versions = new Properties()
    file("../gradle/minecraft-versions.properties").withInputStream {
        versions.load(it)
    }
    repositories {
        maven {
            name = "NeoForged"
            url = "https://maven.neoforged.net/releases"
        }
        gradlePluginPortal()
    }
    plugins {
        id "net.neoforged.gradle.userdev" version versions.getProperty("neoforge_legacy_plugin_version")
    }
}

rootProject.name = "TeamViewRelay-NeoForge-Legacy"
