name: dependency-submission

on:
  push:
    branches: [ "main"]
    paths:
      - 'common/**'
      - 'fabric/**'
      - 'neoforge/**'
  pull_request:
    branches: [ "main"]
    paths:
      - 'common/**'
      - 'fabric/**'
      - 'neoforge/**'

jobs:

  java-dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout sources
      uses: actions/checkout@v6
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v5

